import { defineActivity } from '../define';

export const U01 = [
  defineActivity({
    id: 'U01-A01', unitId: 'U01', title: '엔터티·속성·값 나누기',
    objective: '학교 자료를 엔터티, 속성, 속성값으로 구분한다.',
    estimatedMinutes: 4,
    explanation: '데이터 모델링은 현실의 정보를 표로 정리하는 설계예요. 엔터티는 관리할 대상의 묶음(학생, 강좌), 속성은 그 대상의 특징(이름, 학년), 속성값은 실제로 들어가는 값(가온, 3)이에요.',
    glossary: [
      { term: '엔터티(Entity)', meaning: '관리할 대상의 묶음. 표 하나가 보통 엔터티 하나예요. 예: 학생' },
      { term: '속성(Attribute)', meaning: '엔터티의 특징. 표의 열이에요. 예: 학년' },
      { term: '속성값', meaning: '속성에 실제로 들어가는 값. 표의 칸이에요. 예: 3' },
    ],
    mode: 'simulation', datasetId: 'school',
    prompt: '각 카드가 엔터티인지, 속성인지, 속성값인지 골라 주세요.',
    prediction: {
      prompt: 'students 표에서 "학년(grade)"은 표의 어디에 해당할까요?',
      options: ['행(가로 한 줄)', '열(세로 한 줄)', '표 전체'],
      correctIndex: 1,
      reveal: '학년은 모든 학생이 공통으로 갖는 특징이라 열(속성)이에요.',
    },
    hints: [
      '엔터티는 "~들"을 붙여 셀 수 있는 대상의 묶음이에요(학생들, 강좌들).',
      '"무엇의 무엇"으로 말할 수 있으면 뒤쪽이 속성이에요. 예: 학생의 이름 → 이름은 속성.',
      '따옴표 안의 구체적인 값이나 숫자는 속성값이에요. 학생·강좌·학과는 엔터티예요.',
    ],
    solution: { reasoning: '학생·강좌·학과는 엔터티, 학번·강좌명·학년은 속성, 가온·SQL캠프·3은 속성값이에요.', commonMistakes: ['구체적인 값(가온)을 엔터티로 고르는 것', '속성(학년)을 값으로 고르는 것'] },
    conceptTags: ['엔터티', '속성', '모델링'],
    successMessage: '엔터티·속성·값을 구분했어요.',
    config: {
      kind: 'classify', layout: 'bins',
      items: [
        { id: 'student', label: '학생' }, { id: 'student_id', label: '학번' }, { id: 'gaon', label: "'가온'" },
        { id: 'course', label: '강좌' }, { id: 'course_name', label: '강좌명' }, { id: 'sqlcamp', label: "'SQL캠프'" },
        { id: 'dept', label: '학과' }, { id: 'grade', label: '학년' }, { id: 'three', label: '3' },
      ],
      options: [{ id: 'entity', label: '엔터티' }, { id: 'attribute', label: '속성' }, { id: 'value', label: '속성값' }],
      answer: { source: 'static', map: { student: 'entity', student_id: 'attribute', gaon: 'value', course: 'entity', course_name: 'attribute', sqlcamp: 'value', dept: 'entity', grade: 'attribute', three: 'value' } },
      demoSql: 'SELECT student_id AS 학번, student_name AS 이름, grade AS 학년 FROM students;',
    },
  }),
  defineActivity({
    id: 'U01-A02', unitId: 'U01', title: '인스턴스와 속성 찾기',
    objective: '행(인스턴스)과 열(속성)을 골라 원하는 값 하나를 찾는다.',
    estimatedMinutes: 4,
    explanation: '인스턴스는 엔터티에 속한 하나하나의 대상으로, 표에서 가로 한 줄(행)이에요. 원하는 값을 찾으려면 어느 행(누구)과 어느 열(무엇)인지 정하면 돼요. 아래에서 행과 열을 골라 실제 SQL로 확인해 봐요.',
    glossary: [
      { term: '인스턴스(Instance)', meaning: '엔터티에 속한 하나의 대상. 표의 행 하나예요. 예: 학생 다온' },
      { term: 'SELECT ... FROM ... WHERE', meaning: '어느 열을(SELECT) 어느 표에서(FROM) 어떤 행만(WHERE) 볼지 정하는 SQL 문장' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: "학생 '다온'이라는 인스턴스의 학년 속성값을 찾도록 열과 행을 고르세요.",
    prediction: {
      prompt: 'students 표에는 인스턴스(학생)가 몇 개 있을까요?',
      options: ['4개', '6개', '8개'],
      correctIndex: 1,
      reveal: '학생 한 명이 행 하나이므로 행 수가 인스턴스 수예요.',
      verifySql: 'SELECT COUNT(*) FROM students',
    },
    hints: [
      '열은 "무엇"(속성), 행은 "누구"(인스턴스)예요.',
      '학년은 grade 열이에요. 다온이 몇 번 학생인지 표에서 찾아보세요.',
      "SELECT grade FROM students WHERE student_id = (다온의 번호) 형태가 되면 돼요.",
    ],
    solution: { sql: 'SELECT grade FROM students WHERE student_id = 3;', reasoning: '다온은 student_id 3인 행이고, 학년은 grade 열이에요.', commonMistakes: ['student_name 열을 고르는 것', '다른 학생의 번호를 고르는 것'] },
    conceptTags: ['인스턴스', '속성'],
    successMessage: '행과 열을 골라 다온의 학년을 찾았어요.',
    config: {
      kind: 'row-filter',
      baseSql: 'SELECT student_id, student_name, dept_id, grade FROM students',
      template: 'SELECT {col} FROM students WHERE student_id = {row}',
      slots: [
        { id: 'col', label: '열(속성)', options: [{ label: 'student_name (이름)', value: 'student_name' }, { label: 'dept_id (학과 번호)', value: 'dept_id' }, { label: 'grade (학년)', value: 'grade' }] },
        { id: 'row', label: '행(인스턴스)', options: [1, 2, 3, 4, 5, 6].map((n) => ({ label: `student_id = ${n}`, value: String(n) })) },
      ],
      solutionSql: 'SELECT grade FROM students WHERE student_id = 3',
      ordered: false,
    },
  }),
  defineActivity({
    id: 'U01-A03', unitId: 'U01', title: '개념→논리→물리 모델 연결',
    objective: '모델링 단계별로 하는 일을 구분한다.',
    estimatedMinutes: 4,
    explanation: '모델링은 개념 모델(핵심 대상과 업무 규칙), 논리 모델(속성·식별자·관계·정규화), 물리 모델(실제 DBMS의 테이블·타입·인덱스) 순으로 구체화해요. 갈수록 컴퓨터에 가까워져요.',
    glossary: [
      { term: '개념 모델', meaning: '업무에 필요한 핵심 엔터티와 관계를 큰 그림으로 표현' },
      { term: '논리 모델', meaning: '속성, 식별자, 관계를 정확히 정하고 정규화하는 단계' },
      { term: '물리 모델', meaning: '특정 DBMS에 맞춰 테이블, 데이터 타입, 인덱스를 정하는 단계' },
      { term: '모델링의 특징', meaning: '추상화(공통 특징을 뽑아 일반화) · 단순화(약속된 표기법으로 쉽게 표현) · 명확화(한 가지 뜻으로만 해석되게 정확히 표현)' },
    ],
    mode: 'simulation', datasetId: 'school',
    prompt: '각 작업 카드를 알맞은 모델링 단계에 연결하세요.',
    hints: [
      '사람과 대화하며 큰 그림을 그리면 개념, DBMS에서 실행할 문장을 쓰면 물리예요.',
      '식별자나 정규화처럼 "규칙을 정확히" 정하는 일은 중간 단계예요.',
      '데이터 타입(INTEGER, TEXT)·CREATE TABLE은 물리, 주식별자 결정은 논리예요.',
    ],
    solution: { reasoning: '업무 대화·핵심 엔터티는 개념, 식별자·정규화는 논리, 타입·인덱스·CREATE TABLE은 물리 모델이에요.', commonMistakes: ['정규화를 물리 모델로 고르는 것', '주식별자 결정을 개념 모델로 고르는 것'] },
    conceptTags: ['개념/논리/물리 모델', '모델링'],
    successMessage: '모델링 3단계를 연결했어요.',
    config: {
      kind: 'classify', layout: 'bins',
      items: [
        { id: 'c1', label: '담당 선생님과 이야기하며 학생·강좌·학과가 필요하다고 정리' },
        { id: 'c2', label: '학생이 여러 강좌를 수강한다는 핵심 규칙을 그림으로 표현' },
        { id: 'c3', label: '수강(학생ID, 강좌ID, 점수)에서 (학생ID, 강좌ID)를 주식별자로 결정' },
        { id: 'c4', label: '반복되는 학과명을 별도 엔터티로 분리(정규화)' },
        { id: 'c5', label: 'student_id는 INTEGER, student_name은 TEXT로 데이터 타입 결정' },
        { id: 'c6', label: 'CREATE TABLE enrollment(...) 문장으로 실제 테이블 생성' },
      ],
      options: [{ id: 'conceptual', label: '개념 모델' }, { id: 'logical', label: '논리 모델' }, { id: 'physical', label: '물리 모델' }],
      answer: { source: 'static', map: { c1: 'conceptual', c2: 'conceptual', c3: 'logical', c4: 'logical', c5: 'physical', c6: 'physical' } },
    },
  }),
  defineActivity({
    id: 'U01-A04', unitId: 'U01', title: '도메인에 맞지 않는 값 고치기',
    objective: '속성의 도메인(허용 값 범위)을 지키도록 INSERT 값을 고친다.',
    estimatedMinutes: 4,
    explanation: '도메인은 한 속성이 가질 수 있는 값의 범위예요. students의 grade는 1~3의 정수, dept_id는 departments에 있는 학과 번호만 허용돼요. 실제 DB는 제약조건으로 도메인을 지켜서, 범위를 벗어난 값은 저장을 거부해요.',
    glossary: [
      { term: '도메인(Domain)', meaning: '속성이 가질 수 있는 값의 범위. 예: grade는 1, 2, 3' },
      { term: 'INSERT', meaning: '표에 새 행을 추가하는 SQL 문장' },
      { term: 'CHECK·FOREIGN KEY', meaning: '도메인을 지키게 하는 제약조건. 범위를 벗어나면 오류가 나요' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: "새 학생 '사랑'(학번 9, AI로봇 학과, 1학년)을 추가하려는데 두 값이 도메인을 벗어났어요. 값을 고쳐 실행하세요.",
    prediction: {
      prompt: '지금 SQL을 그대로 실행하면 어떻게 될까요?',
      options: ['그대로 저장된다', '제약조건 오류로 저장되지 않는다', '학년만 자동으로 3으로 바뀐다'],
      correctIndex: 1,
      reveal: 'grade 4는 CHECK(1~3)에, 학과 이름 글자는 정수형 학과 번호(타입·FK)에 맞지 않아 거부돼요.',
    },
    hints: [
      'grade의 도메인은 1~3, dept_id의 도메인은 departments 표에 있는 번호예요.',
      'AI로봇 학과의 번호를 departments 표에서 찾고, 학년은 문제에 적힌 값으로 바꾸세요.',
      "INSERT INTO students VALUES (9, '사랑', 학과번호, 학년); 형태로 숫자 두 개를 고치세요.",
    ],
    solution: { sql: "INSERT INTO students VALUES (9, '사랑', 20, 1);", reasoning: 'AI로봇은 dept_id 20, 1학년은 grade 1이에요. 두 값이 모두 도메인 안에 있어 저장돼요.', commonMistakes: ["dept_id에 'AI로봇' 글자를 넣는 것", '학년을 4로 두는 것'] },
    conceptTags: ['도메인', '제약조건'],
    successMessage: '도메인에 맞게 값을 고쳐 새 학생을 저장했어요.',
    config: {
      kind: 'sql-editor',
      starterSql: "INSERT INTO students VALUES (9, '사랑', 'AI로봇', 4);",
      solutionSql: "INSERT INTO students VALUES (9, '사랑', 20, 1);",
      ordered: true,
      allow: ['insert'],
      stateCheckSql: 'SELECT * FROM students ORDER BY student_id',
      explore: [{ label: '학과 번호 보기', sql: 'SELECT * FROM departments;' }],
    },
  }),
];
