import { defineActivity } from '../define';

export const U02 = [
  defineActivity({
    id: 'U02-A01', unitId: 'U02', title: '학생-수강 ERD 연결',
    objective: '엔터티 사이 관계의 차수·선택성·식별 여부를 정한다.',
    estimatedMinutes: 6,
    explanation: 'ERD는 엔터티와 관계를 그린 그림이에요. 차수는 상대가 몇 개까지 연결되는지(1:1, 1:N, M:N), 선택성은 연결이 없어도 되는지예요. 자식의 기본키에 부모 키가 들어가면 식별 관계, 아니면 비식별 관계예요.',
    glossary: [
      { term: 'ERD', meaning: '엔터티와 관계를 상자와 선으로 그린 설계도' },
      { term: '차수(Cardinality)', meaning: '한 쪽 하나에 상대가 몇 개 연결되는지. 1:1, 1:N, M:N' },
      { term: '선택성(Optionality)', meaning: '관계가 반드시 있어야 하는지(필수), 없어도 되는지(선택)' },
      { term: '식별 관계', meaning: '부모의 키가 자식의 기본키 일부가 되는 관계' },
    ],
    mode: 'simulation', datasetId: 'school',
    prompt: 'ERD의 각 관계 질문에 답해 연결을 완성하세요. 실제 데이터를 보며 판단해도 좋아요.',
    hints: [
      '한 학과에 학생이 몇 명 있을 수 있는지, 한 학생이 강좌를 몇 개 들을 수 있는지 생각해 보세요.',
      '라온·마루처럼 수강 기록이 없는 학생이 있다면 그 관계는 "없어도 되는" 관계예요.',
      'enrollment의 기본키는 (student_id, course_id)예요. students의 기본키에는 dept_id가 없어요.',
    ],
    solution: { reasoning: '학과-학생 1:N, 학생-강좌는 M:N이라 수강 엔터티로 해소해요. 수강 없는 학생이 있으니 선택 관계, 수강의 PK에 course_id가 들어가니 식별 관계, 학생의 PK에는 dept_id가 없으니 비식별 관계예요.', commonMistakes: ['학생-강좌를 1:N으로 고르는 것', 'FK가 있으면 모두 식별 관계라고 생각하는 것'] },
    conceptTags: ['관계', '차수·선택성', '식별/비식별 관계'],
    successMessage: 'ERD의 관계를 모두 연결했어요.',
    config: {
      kind: 'erd',
      entities: [
        { id: 'dept', name: '학과 departments', attributes: ['dept_id (PK)', 'dept_name'] },
        { id: 'student', name: '학생 students', attributes: ['student_id (PK)', 'student_name', 'dept_id (FK)', 'grade'] },
        { id: 'enroll', name: '수강 enrollment', attributes: ['student_id (PK, FK)', 'course_id (PK, FK)', 'score'] },
        { id: 'course', name: '강좌 courses', attributes: ['course_id (PK)', 'course_name'] },
      ],
      relations: [
        { id: 'r1', from: 'dept', to: 'student', question: '학과 하나에 학생은 몇 명까지 연결될까요? (차수)', options: [{ id: '1:1', label: '1:1' }, { id: '1:N', label: '1:N' }, { id: 'M:N', label: 'M:N' }] },
        { id: 'r2', from: 'student', to: 'course', question: '학생과 강좌의 관계 차수는? (수강 표를 빼고 생각)', options: [{ id: '1:1', label: '1:1' }, { id: '1:N', label: '1:N' }, { id: 'M:N', label: 'M:N' }] },
        { id: 'r3', from: 'student', to: 'enroll', question: '학생 쪽에서 수강 행이 없어도 될까요? (선택성)', options: [{ id: 'mandatory', label: '필수: 반드시 1개 이상' }, { id: 'optional', label: '선택: 0개도 가능' }] },
        { id: 'r4', from: 'course', to: 'enroll', question: '강좌-수강 관계는? (course_id가 수강의 기본키 일부)', options: [{ id: 'identifying', label: '식별 관계' }, { id: 'non-identifying', label: '비식별 관계' }] },
        { id: 'r5', from: 'dept', to: 'student', question: '학과-학생 관계는? (dept_id는 학생의 기본키가 아님)', options: [{ id: 'identifying', label: '식별 관계' }, { id: 'non-identifying', label: '비식별 관계' }] },
      ],
      answer: { r1: '1:N', r2: 'M:N', r3: 'optional', r4: 'identifying', r5: 'non-identifying' },
    },
  }),
  defineActivity({
    id: 'U02-A02', unitId: 'U02', title: 'PK·FK와 식별자 고르기',
    objective: '기본키, 외래키, 복합키, 대체키를 실제 스키마에서 구분한다.',
    estimatedMinutes: 7,
    explanation: '기본키(PK)는 행 하나를 유일하게 찾는 열이고, 외래키(FK)는 다른 표의 기본키를 가리키는 열이에요. 열 두 개를 묶어 기본키로 쓰면 복합키예요. 기본키 후보였지만 선택되지 않은 유일한 열은 대체키(UNIQUE)로 둬요.',
    glossary: [
      { term: '기본키(PK)', meaning: '행을 유일하게 구별하는 열. NULL이 될 수 없어요' },
      { term: '외래키(FK)', meaning: '다른 표의 기본키 값을 참조하는 열' },
      { term: '복합키', meaning: '두 개 이상의 열을 묶은 기본키' },
      { term: '대체키', meaning: '유일하지만 기본키로 선택되지 않은 키. UNIQUE로 표시' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '각 열(또는 열 묶음)이 어떤 키인지 고른 뒤, 실제 스키마 조회로 확인하세요.',
    prediction: {
      prompt: 'enrollment 표에서 student_id 하나만으로 행을 유일하게 찾을 수 있을까요?',
      options: ['있다', '없다 — 같은 학생이 여러 강좌를 들어서'],
      correctIndex: 1,
      reveal: '가온(1)은 101, 102 두 강좌를 들어서 student_id만으로는 행이 하나로 정해지지 않아요.',
    },
    hints: [
      '다른 표를 가리키는 열이 FK, 자기 표의 행을 구별하는 열이 PK예요.',
      'enrollment는 학생과 강좌 두 열을 함께 써야 행이 하나로 정해져요.',
      'departments.dept_name은 UNIQUE NOT NULL이지만 기본키는 dept_id예요.',
    ],
    solution: { reasoning: 'students.student_id와 courses.course_id는 PK, students.dept_id와 enrollment.course_id 단독은 FK, enrollment의 (student_id, course_id)는 복합 PK, dept_name은 대체키예요.', commonMistakes: ['enrollment.course_id를 PK로 고르는 것', 'dept_name을 PK로 고르는 것'] },
    conceptTags: ['PK/FK', '식별자'],
    successMessage: 'PK·FK·복합키·대체키를 구분했어요.',
    config: {
      kind: 'classify', layout: 'bins',
      items: [
        { id: 'k1', label: 'students.student_id' }, { id: 'k2', label: 'students.dept_id' },
        { id: 'k3', label: 'enrollment의 (student_id, course_id)' }, { id: 'k4', label: 'enrollment.course_id (단독)' },
        { id: 'k5', label: 'courses.course_id' }, { id: 'k6', label: 'departments.dept_name' },
      ],
      options: [{ id: 'pk', label: '기본키(PK)' }, { id: 'fk', label: '외래키(FK)' }, { id: 'cpk', label: '복합 기본키' }, { id: 'ak', label: '대체키(UNIQUE)' }],
      answer: { source: 'static', map: { k1: 'pk', k2: 'fk', k3: 'cpk', k4: 'fk', k5: 'pk', k6: 'ak' } },
      demoSql: "SELECT m.name AS table_name, p.name AS column_name, p.pk AS pk_order, p.\"notnull\" AS not_null FROM sqlite_schema m JOIN pragma_table_info(m.name) p WHERE m.type = 'table' ORDER BY m.name, p.cid;",
    },
  }),
  defineActivity({
    id: 'U02-A03', unitId: 'U02', title: '수강표 정규화하기',
    objective: '부분 종속과 이행 종속을 없애도록 열을 알맞은 표로 나눈다.',
    estimatedMinutes: 6,
    explanation: '정규화는 한 표에 여러 주제가 섞여 생기는 이상현상(같은 값을 여러 번 고쳐야 하는 문제 등)을 없애려고 표를 나누는 과정이에요. 키의 일부에만 종속된 열(부분 종속)과 다른 일반 열을 거쳐 종속된 열(이행 종속)을 따로 떼어 내요.',
    glossary: [
      { term: '함수 종속', meaning: 'A 값이 정해지면 B 값이 하나로 정해지는 관계. A → B' },
      { term: '부분 종속', meaning: '복합키 중 일부 열에만 종속된 것. 2정규형에서 제거' },
      { term: '이행 종속', meaning: 'A → B → C처럼 다른 일반 열을 거쳐 종속된 것. 3정규형에서 제거' },
      { term: '이상현상', meaning: '중복 때문에 생기는 입력·수정·삭제 문제' },
    ],
    mode: 'executable', datasetId: 'normal',
    prompt: 'enrollment_raw의 각 열을 어느 표로 옮겨야 할지 고르세요. 키 열(student_id, course_id)은 이미 배치돼 있어요.',
    prediction: {
      prompt: "가온(1)의 이름을 바꾸려면 enrollment_raw에서 몇 행을 고쳐야 할까요?",
      options: ['1행', '2행', '6행'],
      correctIndex: 1,
      reveal: '가온은 두 강좌를 들어서 이름이 두 번 저장돼 있어요. 하나만 고치면 데이터가 어긋나요(갱신 이상).',
      verifySql: 'SELECT COUNT(*) || \'행\' FROM enrollment_raw WHERE student_id = 1',
    },
    hints: [
      '각 열이 "무엇이 정해지면" 하나로 정해지는지 생각해 보세요.',
      'student_name은 student_id만, course_name은 course_id만 알면 정해져요. dept_name은 dept_id가 정해요.',
      '점수(score)는 학생과 강좌가 둘 다 정해져야 하나로 정해져요.',
    ],
    solution: { reasoning: 'student_name·dept_id는 students, dept_name은 departments, course_name은 courses, score는 enrollment로 가요. 그러면 각 정보가 한 번만 저장돼요.', commonMistakes: ['dept_name을 students에 남기는 것(이행 종속)', 'score를 students로 옮기는 것'] },
    conceptTags: ['함수종속', '1·2·3정규형', '이상현상'],
    successMessage: '수강표를 정규화해 중복을 없앴어요.',
    config: {
      kind: 'normalize',
      sourceSql: 'SELECT * FROM enrollment_raw ORDER BY student_id, course_id',
      columns: [
        { id: 'student_name', label: 'student_name' }, { id: 'dept_id', label: 'dept_id' }, { id: 'dept_name', label: 'dept_name' },
        { id: 'course_name', label: 'course_name' }, { id: 'score', label: 'score' },
      ],
      tables: [
        { id: 'students', label: 'students(student_id, …)' }, { id: 'departments', label: 'departments(dept_id, …)' },
        { id: 'courses', label: 'courses(course_id, …)' }, { id: 'enrollment', label: 'enrollment(student_id, course_id, …)' },
      ],
      answer: { student_name: 'students', dept_id: 'students', dept_name: 'departments', course_name: 'courses', score: 'enrollment' },
      rejoinSql: 'SELECT s.student_id, s.student_name, s.dept_id, d.dept_name, c.course_id, c.course_name, e.score\nFROM enrollment e\nJOIN students s ON s.student_id = e.student_id\nJOIN departments d ON d.dept_id = s.dept_id\nJOIN courses c ON c.course_id = e.course_id\nORDER BY s.student_id, c.course_id;',
    },
  }),
  defineActivity({
    id: 'U02-A04', unitId: 'U02', title: '관계와 NULL을 결과로 확인',
    objective: '모델의 선택적 관계가 조인 결과의 행 수와 NULL로 나타나는 것을 확인한다.',
    estimatedMinutes: 6,
    explanation: '모델에서 "학생은 수강이 없어도 된다(선택)"고 정하면, 학생과 수강을 연결한 결과에 짝이 없는 학생이 생겨요. 짝이 있는 행만 남기면 그 학생이 사라지고, 모두 남기면 빈칸이 NULL로 채워져요. 함께 처리돼야 하는 변경은 트랜잭션으로 묶어요.',
    glossary: [
      { term: 'JOIN', meaning: '두 표의 행을 같은 키 값으로 이어 붙이는 연산(U07에서 자세히)' },
      { term: 'NULL', meaning: '값이 없거나 알 수 없음을 뜻하는 표시. 0이나 빈 글자와 달라요' },
      { term: '트랜잭션', meaning: '한꺼번에 모두 반영되거나 모두 취소돼야 하는 작업 묶음(U11)' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '두 SQL을 실행해 행 수를 비교하고, 학생이 사라지는 이유를 고르세요.',
    prediction: {
      prompt: '짝이 있는 행만 남기는 첫 번째 SQL(JOIN)의 결과는 몇 행일까요?',
      options: ['6행', '8행', '18행'],
      correctIndex: 0,
      reveal: '수강 행 6개가 각각 학생 한 명과 짝지어져 6행이에요.',
      verifySql: "SELECT COUNT(*) || '행' FROM students s JOIN enrollment e ON s.student_id = e.student_id",
    },
    hints: [
      '수강 기록이 없는 학생이 누구인지 enrollment 표에서 찾아보세요.',
      '첫 번째 SQL은 짝이 있는 행만, 두 번째(LEFT JOIN)는 왼쪽 학생을 모두 남겨요.',
      '라온(4)·마루(5)는 수강 행이 0개예요. 모델에서 이 관계를 무엇이라고 했나요?',
    ],
    solution: { reasoning: '학생-수강은 선택 관계라 수강 행이 0개인 학생이 있어요. 짝만 남기면 그 학생이 빠지고, LEFT JOIN은 남기면서 course_id를 NULL로 채워요.', commonMistakes: ['학생 이름이 NULL이라서 빠졌다고 생각하는 것'] },
    conceptTags: ['관계', 'NULL', '모델과 조인'],
    successMessage: '모델의 선택 관계가 결과의 NULL로 나타나는 것을 확인했어요.',
    config: {
      kind: 'predict-result',
      sql: 'SELECT s.student_name, e.course_id\nFROM students s JOIN enrollment e ON s.student_id = e.student_id\nORDER BY s.student_id, e.course_id;',
      compareSql: [{ label: '모든 학생 남기기(LEFT JOIN)', sql: 'SELECT s.student_name, e.course_id\nFROM students s LEFT JOIN enrollment e ON s.student_id = e.student_id\nORDER BY s.student_id, e.course_id;' }],
      check: {
        prompt: '첫 번째 결과에 라온·마루가 없는 이유는 무엇일까요?',
        options: ['학생-수강이 선택 관계라 짝이 되는 수강 행이 없어서', '두 학생의 이름이 NULL이라서', '트랜잭션이 취소되어서', '두 학생의 학과가 없어서'],
        correctIndex: 0,
        reveal: '두 학생은 수강 행이 없어 짝이 없어요. LEFT JOIN에서는 남고 course_id가 NULL이 돼요.',
      },
    },
  }),
];
