import { defineActivity } from '../define';

export const U03 = [
  defineActivity({
    id: 'U03-A01', unitId: 'U03', title: 'SELECT·FROM 블록 조립',
    objective: 'SELECT와 FROM으로 원하는 열을 조회하는 문장을 만든다.',
    estimatedMinutes: 6,
    explanation: '관계형 DB는 데이터를 행과 열로 된 표(테이블)로 저장해요. SELECT 뒤에는 볼 열을, FROM 뒤에는 그 열이 있는 표를 써요. 열이 여러 개면 쉼표로 구분해요.',
    glossary: [
      { term: '관계형 DB', meaning: '데이터를 표(테이블)들로 저장하고 키로 연결하는 데이터베이스' },
      { term: 'SELECT', meaning: '결과에 보여줄 열을 정하는 절' },
      { term: 'FROM', meaning: '데이터를 가져올 표를 정하는 절' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '블록을 순서대로 눌러 "모든 학생의 이름과 학년"을 조회하는 SQL을 만들고 실행하세요.',
    prediction: {
      prompt: '이 SQL의 결과는 몇 행일까요?',
      options: ['1행', '3행', '6행'],
      correctIndex: 2,
      reveal: '조건이 없으니 students의 모든 행(학생 6명)이 나와요.',
      verifySql: "SELECT COUNT(*) || '행' FROM students",
    },
    hints: [
      'SQL은 SELECT(무엇을) → FROM(어디서) 순서로 써요.',
      '이름 열은 student_name, 학년 열은 grade, 표는 students예요.',
      'SELECT student_name , grade FROM students 순서로 블록을 누르세요.',
    ],
    solution: { sql: 'SELECT student_name, grade FROM students;', reasoning: 'SELECT 뒤에 이름·학년 열을 쉼표로 나열하고 FROM 뒤에 students 표를 써요.', commonMistakes: ['FROM을 SELECT보다 먼저 쓰는 것', '열 사이 쉼표를 빼는 것', 'courses 표를 고르는 것'] },
    conceptTags: ['SELECT', 'FROM'],
    successMessage: 'SELECT와 FROM으로 첫 조회를 실행했어요.',
    config: {
      kind: 'sql-blocks',
      blocks: ['SELECT', 'student_name', ',', 'grade', 'FROM', 'students', 'WHERE', 'courses', '*'],
      solutionSql: 'SELECT student_name, grade FROM students',
      ordered: false,
    },
  }),
  defineActivity({
    id: 'U03-A02', unitId: 'U03', title: '결과 열과 행 예측하기',
    objective: '별칭과 산술식이 결과 열을 어떻게 만드는지 예측한다.',
    estimatedMinutes: 7,
    explanation: 'SELECT에는 열 이름뿐 아니라 grade + 1 같은 계산식도 쓸 수 있어요. 계산 결과는 표에 저장되지 않고 조회할 때 만들어져요. AS 뒤에 별칭을 붙이면 결과 열의 이름을 바꿀 수 있어요.',
    glossary: [
      { term: '산술식', meaning: '+, -, *, / 로 값을 계산하는 식' },
      { term: '별칭(AS)', meaning: '결과 열이나 표에 붙이는 다른 이름. 예: student_name AS 이름' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '먼저 결과의 열 개수를 예측한 뒤 실행하고, 계산된 열의 의미를 고르세요.',
    prediction: {
      prompt: '아래 SQL 결과의 열은 몇 개일까요?',
      options: ['2개', '3개', '4개'],
      correctIndex: 1,
      reveal: 'SELECT 뒤에 쉼표로 나눈 항목이 3개(이름, grade, next_grade)라서 열도 3개예요.',
    },
    hints: [
      'SELECT 뒤의 항목 수가 결과 열 수예요.',
      'next_grade는 grade + 1을 계산해 붙인 이름이에요.',
      'students 표의 열 목록에 next_grade가 있는지 보세요. 없다면 어디서 생겼을까요?',
    ],
    solution: { reasoning: 'next_grade는 조회할 때 grade + 1로 계산해 별칭을 붙인 열이에요. 표에는 저장되지 않아요.', commonMistakes: ['계산한 열이 표에 저장된다고 생각하는 것'] },
    conceptTags: ['별칭', '산술식'],
    successMessage: '별칭과 계산 열을 확인했어요.',
    config: {
      kind: 'predict-result',
      sql: 'SELECT student_name AS 이름, grade, grade + 1 AS next_grade\nFROM students;',
      check: {
        prompt: 'next_grade 열은 무엇일까요?',
        options: ['students 표에 원래 저장된 열', '조회할 때 grade + 1로 계산해 이름을 붙인 열', 'grade 열의 이름만 바꾼 것'],
        correctIndex: 1,
        reveal: '계산식에 AS로 별칭을 붙였어요. 표는 바뀌지 않아요.',
      },
    },
  }),
  defineActivity({
    id: 'U03-A03', unitId: 'U03', title: 'DISTINCT로 중복 없애기',
    objective: 'DISTINCT가 결과의 중복 행을 어떻게 줄이는지 비교한다.',
    estimatedMinutes: 6,
    explanation: '같은 학과 학생이 여러 명이면 dept_id를 조회할 때 같은 값이 여러 번 나와요. SELECT DISTINCT는 결과에서 완전히 같은 행을 하나만 남겨요. 원래 표의 데이터는 바뀌지 않아요.',
    glossary: [{ term: 'DISTINCT', meaning: '결과에서 중복된 행을 하나만 남기는 키워드' }],
    mode: 'executable', datasetId: 'school',
    prompt: '학생들이 속한 학과 번호(dept_id)를 중복 없이 조회하세요. 먼저 지금 SQL을 실행해 중복을 확인해 보세요.',
    prediction: {
      prompt: 'DISTINCT를 붙이면 결과는 몇 행이 될까요?',
      options: ['6행', '4행', '3행'],
      correctIndex: 2,
      reveal: '학생들의 학과 번호는 10, 20, 30 세 가지예요. 학생이 없는 40번 학과는 나오지 않아요.',
      verifySql: "SELECT COUNT(DISTINCT dept_id) || '행' FROM students",
    },
    hints: [
      '같은 값이 반복되는 결과를 한 번씩만 보이게 하는 키워드가 있어요.',
      '그 키워드는 SELECT 바로 뒤에 써요.',
      'SELECT DISTINCT dept_id FROM students;',
    ],
    solution: { sql: 'SELECT DISTINCT dept_id FROM students;', reasoning: 'DISTINCT는 같은 dept_id 행을 하나만 남겨 10, 20, 30이 나와요.', commonMistakes: ['departments 표에서 조회해 학생 없는 40까지 나오는 것'] },
    conceptTags: ['DISTINCT'],
    successMessage: 'DISTINCT로 중복 행을 줄였어요.',
    config: {
      kind: 'sql-editor',
      starterSql: 'SELECT dept_id FROM students;',
      solutionSql: 'SELECT DISTINCT dept_id FROM students',
      ordered: false,
      blocks: ['DISTINCT', 'dept_id', 'FROM', 'students'],
    },
  }),
  defineActivity({
    id: 'U03-A04', unitId: 'U03', title: 'SQL 논리적 처리 순서',
    objective: 'SELECT 문이 처리되는 논리적 순서를 정렬한다.',
    estimatedMinutes: 6,
    explanation: 'SQL은 쓰는 순서와 처리되는 순서가 달라요. DB는 표를 먼저 정하고(FROM), 행을 거르고, 묶고, 묶음을 거른 뒤에야 보여줄 열(SELECT)을 정하고 마지막에 정렬해요. 그래서 SELECT의 별칭은 ORDER BY에서는 쓸 수 있지만 WHERE에서는 쓸 수 없어요.',
    glossary: [{ term: '논리적 처리 순서', meaning: 'DB가 SELECT 문의 각 절을 해석하는 순서' }],
    mode: 'simulation', datasetId: 'school',
    prompt: '각 절에 처리 순서 번호(1~6)를 하나씩 붙이세요.',
    hints: [
      '어느 표인지 알아야 행을 거를 수 있어요. 가장 먼저는 표를 정하는 절이에요.',
      '그룹을 만든 다음에야 그룹 조건(HAVING)을 볼 수 있어요.',
      'FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY',
    ],
    solution: { reasoning: 'FROM(1) → WHERE(2) → GROUP BY(3) → HAVING(4) → SELECT(5) → ORDER BY(6) 순서예요.', commonMistakes: ['SELECT를 1번으로 두는 것', 'HAVING을 GROUP BY보다 먼저 두는 것'] },
    conceptTags: ['논리적 처리 순서'],
    successMessage: 'SQL의 논리적 처리 순서를 정렬했어요.',
    config: {
      kind: 'classify', layout: 'order',
      items: [
        { id: 'select', label: 'SELECT' }, { id: 'from', label: 'FROM' }, { id: 'where', label: 'WHERE' },
        { id: 'groupby', label: 'GROUP BY' }, { id: 'having', label: 'HAVING' }, { id: 'orderby', label: 'ORDER BY' },
      ],
      options: ['1', '2', '3', '4', '5', '6'].map((n) => ({ id: n, label: `${n}번째` })),
      answer: { source: 'static', map: { from: '1', where: '2', groupby: '3', having: '4', select: '5', orderby: '6' } },
    },
  }),
];
