import { defineActivity } from '../define';

const STUDENT_COLS = 'SELECT student_id, student_name, dept_id, grade FROM students';

export const U04 = [
  defineActivity({
    id: 'U04-A01', unitId: 'U04', title: '조건으로 행 고르기',
    objective: '비교 연산자로 WHERE 조건을 바꾸며 선택되는 행을 본다.',
    estimatedMinutes: 6,
    explanation: 'WHERE는 조건이 참(TRUE)인 행만 남겨요. 비교 연산자는 =, <>, >, >=, <, <= 가 있어요. 조건을 바꾸면 어떤 행이 남는지 표에서 바로 확인할 수 있어요.',
    glossary: [
      { term: 'WHERE', meaning: '조건이 참인 행만 남기는 절' },
      { term: '비교 연산자', meaning: '= (같다), <> (다르다), >, >=, <, <=' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '연산자와 값을 바꿔 "2학년 이상" 학생만 남기세요.',
    prediction: {
      prompt: '2학년 이상인 학생은 몇 명일까요?',
      options: ['3명', '5명', '6명'],
      correctIndex: 1,
      reveal: '1학년인 마루만 빠지고 5명이 남아요.',
      verifySql: "SELECT COUNT(*) || '명' FROM students WHERE grade >= 2",
    },
    hints: [
      '"이상"은 그 값을 포함해요.',
      '포함하려면 >=, 포함하지 않으려면 > 를 써요.',
      'grade >= 2 또는 grade > 1 이 같은 결과를 내요.',
    ],
    solution: { sql: `${STUDENT_COLS} WHERE grade >= 2;`, reasoning: 'grade >= 2는 2학년과 3학년을 남겨요. grade > 1도 같은 행을 남겨요.', commonMistakes: ['grade > 2로 2학년을 빼는 것'] },
    conceptTags: ['WHERE', '비교'],
    successMessage: '조건으로 2학년 이상 학생을 골랐어요.',
    config: {
      kind: 'row-filter',
      baseSql: STUDENT_COLS,
      template: `${STUDENT_COLS} WHERE grade {op} {val}`,
      slots: [
        { id: 'op', label: '연산자', options: ['=', '<>', '>', '>=', '<', '<='].map((o) => ({ label: o, value: o })) },
        { id: 'val', label: '값', options: ['1', '2', '3'].map((v) => ({ label: v, value: v })) },
      ],
      solutionSql: `${STUDENT_COLS} WHERE grade >= 2`,
      ordered: false,
    },
  }),
  defineActivity({
    id: 'U04-A02', unitId: 'U04', title: 'AND/OR와 괄호',
    objective: '괄호 위치에 따라 AND/OR 조건 결과가 달라지는 것을 비교한다.',
    estimatedMinutes: 6,
    explanation: 'AND는 두 조건이 모두 참, OR는 하나라도 참이면 참이에요. 괄호가 없으면 AND를 OR보다 먼저 계산해요. 그래서 "A 또는 B이면서 C"는 (A OR B) AND C처럼 괄호로 묶어야 해요.',
    glossary: [
      { term: 'AND / OR / NOT', meaning: '그리고 / 또는 / 아니다. 조건을 조합하는 논리 연산자' },
      { term: '우선순위', meaning: '괄호 > NOT > AND > OR 순서로 먼저 계산해요' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '"AI컴퓨터(10) 또는 AI로봇(20) 학과이면서 3학년"인 학생만 남도록 괄호 위치를 고르세요.',
    prediction: {
      prompt: '괄호 없이 dept_id = 10 OR dept_id = 20 AND grade = 3 을 실행하면 몇 명이 나올까요?',
      options: ['3명', '4명', '5명'],
      correctIndex: 1,
      reveal: 'AND를 먼저 계산해 "10번 학과 전체 또는 (20번 학과 3학년)"이 되어 바다(10번, 2학년)까지 4명이 나와요.',
      verifySql: "SELECT COUNT(*) || '명' FROM students WHERE dept_id = 10 OR dept_id = 20 AND grade = 3",
    },
    hints: [
      'AND가 OR보다 먼저 계산돼요.',
      '"10 또는 20"을 먼저 하나로 묶어야 해요.',
      '(dept_id = 10 OR dept_id = 20) AND grade = 3',
    ],
    solution: { sql: `${STUDENT_COLS} WHERE (dept_id = 10 OR dept_id = 20) AND grade = 3;`, reasoning: '괄호로 학과 조건을 먼저 묶으면 가온·나래·라온 3명이 남아요.', commonMistakes: ['괄호를 빼서 바다(2학년)까지 나오는 것'] },
    conceptTags: ['AND/OR/NOT', '괄호'],
    successMessage: '괄호로 AND/OR 계산 순서를 바로잡았어요.',
    config: {
      kind: 'row-filter',
      baseSql: STUDENT_COLS,
      template: `${STUDENT_COLS} WHERE {cond}`,
      slots: [{ id: 'cond', label: '조건', options: [
        { label: 'dept_id = 10 OR dept_id = 20 AND grade = 3', value: 'dept_id = 10 OR dept_id = 20 AND grade = 3' },
        { label: '(dept_id = 10 OR dept_id = 20) AND grade = 3', value: '(dept_id = 10 OR dept_id = 20) AND grade = 3' },
        { label: 'dept_id = 10 OR (dept_id = 20 AND grade = 3)', value: 'dept_id = 10 OR (dept_id = 20 AND grade = 3)' },
        { label: 'NOT (dept_id = 30) AND grade = 3', value: 'NOT (dept_id = 30) AND grade = 3' },
      ] }],
      solutionSql: `${STUDENT_COLS} WHERE (dept_id = 10 OR dept_id = 20) AND grade = 3`,
      ordered: false,
    },
  }),
  defineActivity({
    id: 'U04-A03', unitId: 'U04', title: 'LIKE 패턴 맞추기',
    objective: 'LIKE의 %와 _로 문자열 패턴 조건을 만든다.',
    estimatedMinutes: 6,
    explanation: "LIKE는 글자 패턴으로 행을 골라요. %는 0개 이상의 아무 글자, _는 정확히 한 글자를 뜻해요. '%캠프'는 '캠프'로 끝나는 값, '_I%'는 두 번째 글자가 I인 값이에요.",
    glossary: [
      { term: 'LIKE', meaning: '문자열이 패턴과 맞는지 비교하는 연산자' },
      { term: '% / _', meaning: '% = 0개 이상의 아무 글자, _ = 정확히 한 글자' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: "학과명에 '콘텐츠'가 들어 있는 학과만 남는 패턴을 고르세요.",
    prediction: {
      prompt: "dept_name LIKE '콘텐츠%' 는 'AI콘텐츠디자인'과 맞을까요?",
      options: ['맞다', '맞지 않다'],
      correctIndex: 1,
      reveal: "'콘텐츠%'는 '콘텐츠'로 시작하는 값만 맞아요. 앞에 'AI'가 있어 맞지 않아요.",
    },
    hints: [
      "'들어 있다'는 앞뒤에 무엇이 와도 된다는 뜻이에요.",
      '앞뒤 모두에 0개 이상의 글자를 허용하는 기호를 붙여요.',
      "'%콘텐츠%' (앞에 정확히 두 글자가 있다면 '__콘텐츠%'도 같은 결과)",
    ],
    solution: { sql: "SELECT dept_id, dept_name FROM departments WHERE dept_name LIKE '%콘텐츠%';", reasoning: "'%콘텐츠%'는 앞뒤에 어떤 글자가 와도 '콘텐츠'가 들어 있으면 맞아요.", commonMistakes: ["'콘텐츠%'로 시작 위치를 고정하는 것", '_를 %처럼 여러 글자로 생각하는 것'] },
    conceptTags: ['LIKE'],
    dialectNotes: ['SQLite의 LIKE는 영문 대소문자를 구분하지 않아요. Oracle은 기본적으로 구분해요.'],
    successMessage: 'LIKE 패턴으로 원하는 학과를 찾았어요.',
    config: {
      kind: 'row-filter',
      baseSql: 'SELECT dept_id, dept_name FROM departments',
      template: 'SELECT dept_id, dept_name FROM departments WHERE dept_name LIKE {pattern}',
      slots: [{ id: 'pattern', label: '패턴', options: ["'콘텐츠%'", "'%콘텐츠'", "'%콘텐츠%'", "'_콘텐츠%'", "'__콘텐츠%'"].map((p) => ({ label: p, value: p })) }],
      solutionSql: "SELECT dept_id, dept_name FROM departments WHERE dept_name LIKE '%콘텐츠%'",
      ordered: false,
    },
  }),
  defineActivity({
    id: 'U04-A04', unitId: 'U04', title: 'NULL과 NOT IN 함정 고치기',
    objective: 'NULL이 포함된 NOT IN과 NOT EXISTS의 차이를 이해한다.',
    estimatedMinutes: 7,
    explanation: 'NULL은 값이 없거나 알려지지 않았다는 뜻이에요. NULL과 비교한 결과는 TRUE나 FALSE가 아닌 UNKNOWN이 될 수 있어요. WHERE는 TRUE인 행만 남겨요.',
    glossary: [
      { term: 'NULL', meaning: '값이 없거나 알 수 없음. 0이나 빈 문자열과 달라요' },
      { term: '3값 논리', meaning: 'TRUE, FALSE, UNKNOWN 세 가지 결과로 조건을 판단하는 규칙' },
      { term: 'IS NULL', meaning: 'NULL인지 확인하는 올바른 방법. = NULL은 항상 UNKNOWN' },
      { term: 'NOT EXISTS', meaning: '서브쿼리 결과 행이 하나도 없으면 참' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '수강 기록이 없는 학생의 student_id를 NOT EXISTS로 찾아 학번 순으로 조회하세요. 먼저 탐색 SQL로 NOT IN (1, NULL) 결과를 확인해 보세요.',
    prediction: {
      prompt: 'SELECT student_id FROM students WHERE student_id NOT IN (1, NULL); 의 결과는?',
      options: ['2~6번 다섯 행', '0행', '오류'],
      correctIndex: 1,
      reveal: '결과 0행은 데이터가 없어서가 아니라, NULL과 비교한 조건이 UNKNOWN이 되기 때문이에요.',
      verifySql: "SELECT COUNT(*) || '행' FROM students WHERE student_id NOT IN (1, NULL)",
    },
    hints: [
      "'해당 학생의 수강 행이 없는 경우'를 찾으면 돼요.",
      '서브쿼리에서 바깥 학생의 student_id와 enrollment.student_id를 연결하세요.',
      'SELECT s.student_id FROM students s WHERE NOT EXISTS (SELECT 1 FROM enrollment e WHERE e.student_id = s.student_id) ORDER BY ...',
    ],
    solution: {
      sql: 'SELECT s.student_id FROM students s WHERE NOT EXISTS (SELECT 1 FROM enrollment e WHERE e.student_id = s.student_id) ORDER BY s.student_id;',
      reasoning: '학생마다 그 학생의 수강 행이 있는지 확인해 없으면 남겨요. 결과는 4, 5예요. enrollment.student_id는 NOT NULL이라 그 열 자체에는 NULL이 없어요. 위의 0행은 비교 목록에 직접 넣은 NULL 때문이에요.',
      commonMistakes: ['NOT IN 목록에 NULL이 있으면 결과가 0행이 되는 것', '= NULL로 NULL을 찾으려는 것'],
    },
    conceptTags: ['NULL', '3값 논리', 'IS NULL', 'NOT EXISTS'],
    successMessage: 'NOT EXISTS로 수강 기록 없는 학생을 찾았어요.',
    config: {
      kind: 'sql-editor',
      starterSql: 'SELECT s.student_id\nFROM students s\nWHERE NOT EXISTS (\n  SELECT 1 FROM enrollment e WHERE ...\n)\nORDER BY s.student_id;',
      solutionSql: 'SELECT s.student_id FROM students s WHERE NOT EXISTS (SELECT 1 FROM enrollment e WHERE e.student_id = s.student_id) ORDER BY s.student_id',
      ordered: true,
      explore: [
        { label: 'NOT IN (1, NULL) 실행', sql: 'SELECT student_id FROM students WHERE student_id NOT IN (1, NULL);' },
        { label: '학생별 TRUE/FALSE/UNKNOWN 보기', sql: "SELECT student_id,\n  CASE student_id NOT IN (1, NULL) WHEN 1 THEN 'TRUE' WHEN 0 THEN 'FALSE' ELSE 'UNKNOWN' END AS 판정\nFROM students;" },
      ],
    },
  }),
];
