import { defineActivity } from '../define';

export const U05 = [
  defineActivity({
    id: 'U05-A01', unitId: 'U05', title: '문자열 함수 입력과 출력',
    objective: '대표 문자열 함수가 값을 어떻게 바꾸는지 연결한다.',
    estimatedMinutes: 5,
    explanation: '함수는 값을 받아 새 값을 돌려줘요. UPPER는 대문자로, LENGTH는 글자 수를, SUBSTR(문자, 시작, 길이)는 일부를 잘라 줘요. TRIM은 앞뒤 공백을 없애고, ||는 두 문자열을 이어 붙여요.',
    glossary: [
      { term: '단일행 함수', meaning: '행마다 값 하나를 받아 값 하나를 돌려주는 함수' },
      { term: 'SUBSTR(s, 시작, 길이)', meaning: '시작 위치(1부터)에서 길이만큼 잘라냄' },
      { term: '||', meaning: '문자열 이어 붙이기(Oracle·SQLite). SQL Server는 +' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '각 함수 식의 결과를 고른 뒤, 실제 SQLite 실행으로 확인하세요.',
    hints: [
      'LENGTH는 바이트가 아니라 글자 수를 세요(SQLite 기준).',
      "SUBSTR('AI컴퓨터', 3, 2)는 세 번째 글자부터 두 글자예요.",
      "REPLACE(원본, 찾을 글자, 바꿀 글자) — '캠프'를 'Camp'로 바꿔요.",
    ],
    solution: { reasoning: "UPPER('sql')=SQL, LENGTH('SQL캠프')=5, SUBSTR('AI컴퓨터',3,2)=컴퓨, TRIM('  숲  ')=숲, REPLACE→IoTCamp, 'AI'||'캠프'=AI캠프예요.", commonMistakes: ['SUBSTR 시작 위치를 0부터 세는 것'] },
    conceptTags: ['문자열 함수'],
    dialectNotes: ['SQL Server는 LENGTH 대신 LEN, SUBSTR 대신 SUBSTRING, || 대신 +를 써요.', 'Oracle의 LENGTH는 글자 수, LENGTHB는 바이트 수예요.'],
    successMessage: '문자열 함수의 입력과 출력을 연결했어요.',
    config: {
      kind: 'classify', layout: 'bins',
      items: [
        { id: 'f1', label: "UPPER('sql')" }, { id: 'f2', label: "LENGTH('SQL캠프')" }, { id: 'f3', label: "SUBSTR('AI컴퓨터', 3, 2)" },
        { id: 'f4', label: "TRIM('  숲  ')" }, { id: 'f5', label: "REPLACE('IoT캠프', '캠프', 'Camp')" }, { id: 'f6', label: "'AI' || '캠프'" },
      ],
      options: ['SQL', '5', '컴퓨', '숲', 'IoTCamp', 'AI캠프', '8', 'AI'].map((v) => ({ id: v, label: v })),
      answer: { source: 'sql', sql: "SELECT 'f1', UPPER('sql') UNION ALL SELECT 'f2', CAST(LENGTH('SQL캠프') AS TEXT) UNION ALL SELECT 'f3', SUBSTR('AI컴퓨터', 3, 2) UNION ALL SELECT 'f4', TRIM('  숲  ') UNION ALL SELECT 'f5', REPLACE('IoT캠프', '캠프', 'Camp') UNION ALL SELECT 'f6', 'AI' || '캠프'" },
      demoSql: "SELECT UPPER('sql') AS f1, LENGTH('SQL캠프') AS f2, SUBSTR('AI컴퓨터', 3, 2) AS f3, TRIM('  숲  ') AS f4, REPLACE('IoT캠프', '캠프', 'Camp') AS f5, 'AI' || '캠프' AS f6;",
    },
  }),
  defineActivity({
    id: 'U05-A02', unitId: 'U05', title: 'ROUND와 형변환 실험',
    objective: '정수 나눗셈과 형변환, ROUND의 자릿수를 실험한다.',
    estimatedMinutes: 5,
    explanation: 'SQLite에서 정수끼리 나누면 소수점 아래를 버린 정수가 나와요. 한쪽을 3.0처럼 실수로 바꾸거나 CAST로 형변환하면 소수까지 계산돼요. ROUND(값, n)은 소수 n째 자리까지 반올림해요.',
    glossary: [
      { term: '형변환(CAST)', meaning: '값의 자료형을 바꿈. 예: CAST(3 AS REAL) → 3.0' },
      { term: 'ROUND(x, n)', meaning: 'x를 소수 n째 자리까지 반올림' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: 'IoT캠프(102) 점수를 3으로 나눈 값을 소수 첫째 자리까지 반올림해 보이도록 고르세요.',
    prediction: {
      prompt: 'SQLite에서 SELECT 80 / 3; 의 결과는?',
      options: ['26', '26.67', '26.666…', '오류'],
      correctIndex: 0,
      reveal: '정수 ÷ 정수는 정수 나눗셈이라 26이에요. DBMS마다 규칙이 달라 시험에서는 자료형을 꼭 확인해요.',
      verifySql: 'SELECT 80 / 3',
    },
    hints: [
      '정수끼리 나누면 소수점이 사라져요.',
      '나누는 수를 실수(3.0)로 바꾸거나 CAST(3 AS REAL)을 써요.',
      'ROUND(score / 3.0, 1)',
    ],
    solution: { sql: 'SELECT student_id, score, ROUND(score / 3.0, 1) AS 환산 FROM enrollment WHERE course_id = 102;', reasoning: '3.0으로 나누면 실수 나눗셈이 되고 ROUND(…, 1)이 소수 첫째 자리까지 남겨요. 80/3.0=26.7, 70/3.0=23.3이에요.', commonMistakes: ['정수 3으로 나눠 26, 23만 나오는 것', 'ROUND 자릿수를 0으로 두는 것'] },
    conceptTags: ['숫자 함수', '형변환'],
    dialectNotes: ['Oracle은 정수 ÷ 정수도 소수 결과를 내요. SQL Server는 SQLite처럼 정수 나눗셈을 해요.', 'Oracle은 TO_CHAR/TO_NUMBER/TO_DATE, SQL Server는 CONVERT/CAST로 형변환해요.'],
    successMessage: '형변환과 ROUND로 환산 점수를 만들었어요.',
    config: {
      kind: 'row-filter',
      baseSql: 'SELECT student_id, score FROM enrollment WHERE course_id = 102',
      template: 'SELECT student_id, score, ROUND(score / {div}, {digits}) AS 환산 FROM enrollment WHERE course_id = 102',
      slots: [
        { id: 'div', label: '나누는 수', options: [{ label: '3 (정수)', value: '3' }, { label: '3.0 (실수)', value: '3.0' }, { label: 'CAST(3 AS REAL)', value: 'CAST(3 AS REAL)' }] },
        { id: 'digits', label: 'ROUND 자릿수', options: ['0', '1', '2'].map((d) => ({ label: d, value: d })) },
      ],
      solutionSql: 'SELECT student_id, score, ROUND(score / 3.0, 1) AS 환산 FROM enrollment WHERE course_id = 102',
      ordered: false,
    },
  }),
  defineActivity({
    id: 'U05-A03', unitId: 'U05', title: 'COALESCE와 NULLIF',
    objective: 'COALESCE와 NULLIF로 NULL 값이 어떻게 바뀌는지 본다.',
    estimatedMinutes: 5,
    explanation: 'COALESCE(a, b, …)는 왼쪽부터 처음으로 NULL이 아닌 값을 돌려줘요. NULLIF(a, b)는 a와 b가 같으면 NULL, 다르면 a를 돌려줘요. 화면에 NULL 대신 0을 보이고 싶을 때 COALESCE를 써요.',
    glossary: [
      { term: 'COALESCE', meaning: '처음으로 NULL이 아닌 값을 돌려주는 표준 함수' },
      { term: 'NULLIF(a, b)', meaning: 'a = b이면 NULL, 아니면 a' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '점수가 NULL인 행은 0으로 보이도록 식을 고르세요(학생·강좌 순 정렬).',
    prediction: {
      prompt: 'NULLIF(score, 0)을 쓰면 다온의 SQL캠프(NULL) 행은 어떻게 보일까요?',
      options: ['0', 'NULL 그대로', '오류'],
      correctIndex: 1,
      reveal: 'NULLIF는 같은 값을 NULL로 바꾸는 함수라, NULL을 0으로 바꾸지 못해요.',
    },
    hints: [
      'NULL을 다른 값으로 "채우는" 함수가 필요해요.',
      '처음으로 NULL이 아닌 값을 고르는 함수예요.',
      'COALESCE(score, 0)',
    ],
    solution: { sql: 'SELECT student_id, course_id, COALESCE(score, 0) AS 점수표시 FROM enrollment ORDER BY student_id, course_id;', reasoning: 'COALESCE(score, 0)은 score가 NULL이면 0, 아니면 score를 돌려줘요.', commonMistakes: ['NULLIF를 NULL 채우기로 착각하는 것', "'NULL' 글자로 채우는 것"] },
    conceptTags: ['COALESCE', 'NULLIF', 'NULL'],
    dialectNotes: ['Oracle NVL(score, 0), SQL Server ISNULL(score, 0)이 같은 역할을 해요. SQLite에서도 IFNULL을 쓸 수 있어요.'],
    successMessage: 'COALESCE로 NULL을 0으로 보여줬어요.',
    config: {
      kind: 'row-filter',
      baseSql: 'SELECT student_id, course_id, score FROM enrollment',
      template: 'SELECT student_id, course_id, {expr} AS 점수표시 FROM enrollment ORDER BY student_id, course_id',
      slots: [{ id: 'expr', label: '식', options: ['score', 'COALESCE(score, 0)', 'NULLIF(score, 0)', 'NULLIF(score, 90)', "COALESCE(score, 'NULL')"].map((v) => ({ label: v, value: v })) }],
      solutionSql: 'SELECT student_id, course_id, COALESCE(score, 0) FROM enrollment ORDER BY student_id, course_id',
      ordered: true,
    },
  }),
  defineActivity({
    id: 'U05-A04', unitId: 'U05', title: 'CASE로 등급표 만들기',
    objective: 'CASE 식으로 점수 구간에 따라 등급을 붙인다.',
    estimatedMinutes: 6,
    explanation: 'CASE WHEN 조건 THEN 값 … ELSE 값 END는 위에서부터 처음 참인 조건의 값을 돌려줘요. 순서가 중요해서 90 이상을 80 이상보다 먼저 써야 해요. NULL은 어떤 비교도 참이 아니라 ELSE로 가요.',
    glossary: [{ term: 'CASE', meaning: '조건에 따라 다른 값을 고르는 식. 위에서부터 처음 참인 THEN 값' }],
    mode: 'executable', datasetId: 'school',
    prompt: "수강 행마다 90점 이상 'A', 80점 이상 'B', 그 외(NULL 포함) 'C' 등급을 student_id, course_id, 등급 열로 조회하세요.",
    prediction: {
      prompt: "점수가 NULL인 다온의 SQL캠프 행은 어떤 등급이 될까요?",
      options: ["'A'", "'C' (ELSE)", 'NULL'],
      correctIndex: 1,
      reveal: 'NULL >= 90, NULL >= 80 모두 참이 아니어서 ELSE로 가요.',
    },
    hints: [
      'CASE WHEN … THEN … WHEN … THEN … ELSE … END 형식이에요.',
      '높은 기준(90)부터 순서대로 쓰세요.',
      "CASE WHEN score >= 90 THEN 'A' WHEN score >= 80 THEN 'B' ELSE 'C' END",
    ],
    solution: { sql: "SELECT student_id, course_id, CASE WHEN score >= 90 THEN 'A' WHEN score >= 80 THEN 'B' ELSE 'C' END AS 등급 FROM enrollment;", reasoning: '90 이상이 먼저 A로 걸러지고, 남은 80 이상이 B, 나머지와 NULL이 C예요.', commonMistakes: ['80 이상을 먼저 써서 90점도 B가 되는 것', 'ELSE를 빼서 NULL 등급이 생기는 것'] },
    conceptTags: ['CASE'],
    dialectNotes: ["Oracle의 DECODE(score, 90, 'A', 'C')는 '같다' 비교만 하는 CASE의 축약형이에요(SQLite에는 없음)."],
    successMessage: 'CASE로 점수 등급표를 만들었어요.',
    config: {
      kind: 'sql-editor',
      starterSql: "SELECT student_id, course_id,\n  CASE\n    WHEN score >= 90 THEN 'A'\n    -- 이어서 작성하세요\n  END AS 등급\nFROM enrollment;",
      solutionSql: "SELECT student_id, course_id, CASE WHEN score >= 90 THEN 'A' WHEN score >= 80 THEN 'B' ELSE 'C' END AS 등급 FROM enrollment",
      ordered: false,
      blocks: ['WHEN', 'THEN', 'ELSE', "'B'", "'C'", 'score >= 80'],
    },
  }),
];
