import { defineActivity } from '../define';

export const U06 = [
  defineActivity({
    id: 'U06-A01', unitId: 'U06', title: '행을 그룹 상자에 넣기',
    objective: 'GROUP BY가 행을 묶고 묶음마다 집계하는 과정을 직접 해 본다.',
    estimatedMinutes: 6,
    explanation: 'GROUP BY 열은 그 열 값이 같은 행끼리 한 묶음(그룹)으로 모아요. 집계 함수(COUNT, SUM, AVG, MIN, MAX)는 그룹마다 값 하나를 계산해요. 그래서 결과 행 수는 그룹 수와 같아요.',
    glossary: [
      { term: 'GROUP BY', meaning: '같은 값을 가진 행끼리 묶는 절' },
      { term: '집계 함수', meaning: '여러 행을 받아 값 하나를 돌려주는 함수. COUNT, SUM, AVG, MIN, MAX' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '수강 행을 강좌 상자에 하나씩 넣고, 각 상자의 행 수(COUNT(*))를 적으세요.',
    prediction: {
      prompt: '강좌별로 묶으면 결과는 몇 행일까요? (수강생이 있는 강좌만)',
      options: ['2행', '3행', '6행'],
      correctIndex: 0,
      reveal: '수강 행에 나오는 강좌는 SQL캠프, IoT캠프 두 가지라 2개 그룹이에요.',
      verifySql: "SELECT COUNT(DISTINCT course_id) || '행' FROM enrollment",
    },
    hints: [
      '각 행의 강좌명을 보고 같은 강좌끼리 모으세요.',
      'COUNT(*)는 상자 안의 행 개수예요(점수가 NULL이어도 셈).',
      'SQL캠프 상자에는 학생 1, 2, 3의 행이 들어가요.',
    ],
    solution: { sql: 'SELECT c.course_name, COUNT(*) FROM enrollment e JOIN courses c ON c.course_id = e.course_id GROUP BY c.course_name;', reasoning: 'SQL캠프 3행, IoT캠프 3행이에요. AI캠프는 수강 행이 없어 그룹이 생기지 않아요.', commonMistakes: ['점수가 NULL인 행을 세지 않는 것(COUNT(*)는 셈)'] },
    conceptTags: ['GROUP BY', '집계 함수'],
    successMessage: '행을 그룹으로 묶고 개수를 셌어요.',
    config: {
      kind: 'group-visualizer',
      rowsSql: "SELECT e.student_id || '-' || e.course_id AS row_id, e.student_id, c.course_name, e.score FROM enrollment e JOIN courses c ON c.course_id = e.course_id ORDER BY e.student_id, e.course_id",
      groupOfRowSql: "SELECT e.student_id || '-' || e.course_id, c.course_name FROM enrollment e JOIN courses c ON c.course_id = e.course_id",
      aggregateSql: 'SELECT c.course_name, COUNT(*) FROM enrollment e JOIN courses c ON c.course_id = e.course_id GROUP BY c.course_name',
      aggregateLabel: 'COUNT(*)',
      groupSql: 'SELECT c.course_name, COUNT(*) AS cnt\nFROM enrollment e JOIN courses c ON c.course_id = e.course_id\nGROUP BY c.course_name;',
    },
  }),
  defineActivity({
    id: 'U06-A02', unitId: 'U06', title: 'COUNT(*)와 COUNT(score)',
    objective: '집계 함수가 NULL을 어떻게 다루는지 비교한다.',
    estimatedMinutes: 6,
    explanation: 'COUNT(*)는 행 자체를 세고, COUNT(열)은 그 열이 NULL이 아닌 행만 세요. SUM, AVG, MIN, MAX도 NULL을 빼고 계산해요. 그래서 AVG(score)는 NULL 행을 분모에 넣지 않아요.',
    glossary: [
      { term: 'COUNT(*)', meaning: 'NULL과 상관없이 행 수를 셈' },
      { term: 'COUNT(열)', meaning: '그 열이 NULL이 아닌 행만 셈' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '실행해 세 값을 확인하고, AVG(score)가 어떻게 계산됐는지 고르세요.',
    prediction: {
      prompt: 'COUNT(*)와 COUNT(score)는 각각 얼마일까요?',
      options: ['6, 6', '6, 5', '5, 5', '5, 6'],
      correctIndex: 1,
      reveal: '수강 행은 6개, 그중 점수가 있는 행은 5개예요.',
      verifySql: "SELECT COUNT(*) || ', ' || COUNT(score) FROM enrollment",
    },
    hints: [
      'NULL이 있는 행은 다온의 SQL캠프 하나예요.',
      'AVG는 NULL이 아닌 값의 합 ÷ NULL이 아닌 값의 개수예요.',
      '(90 + 80 + 90 + 70 + 80) ÷ 5',
    ],
    solution: { sql: 'SELECT COUNT(*) AS row_count, COUNT(score) AS score_count, AVG(score) AS avg_score FROM enrollment;', reasoning: 'COUNT(*)=6, COUNT(score)=5, AVG(score)=410÷5=82예요.', commonMistakes: ['AVG를 410÷6으로 계산하는 것'] },
    conceptTags: ['COUNT(*)와 COUNT(열)', 'NULL 집계'],
    successMessage: 'COUNT(*)와 COUNT(score)의 차이를 확인했어요.',
    config: {
      kind: 'predict-result',
      sql: 'SELECT COUNT(*) AS row_count, COUNT(score) AS score_count, AVG(score) AS avg_score\nFROM enrollment;',
      compareSql: [{ label: 'NULL을 0으로 보고 평균', sql: 'SELECT AVG(COALESCE(score, 0)) AS avg_with_zero FROM enrollment;' }],
      check: {
        prompt: 'AVG(score) = 82는 어떻게 계산됐을까요?',
        options: ['410 ÷ 6 (모든 행)', '410 ÷ 5 (NULL 행 제외)', '90과 70의 중간값'],
        correctIndex: 1,
        reveal: '집계 함수는 NULL을 빼고 계산해요. NULL을 0으로 보려면 COALESCE를 먼저 써요.',
      },
    },
  }),
  defineActivity({
    id: 'U06-A03', unitId: 'U06', title: 'WHERE와 HAVING 자리 고치기',
    objective: '그룹 조건은 HAVING에 써야 하는 이유를 오류를 고치며 익힌다.',
    estimatedMinutes: 6,
    explanation: 'WHERE는 그룹을 만들기 전에 행 하나하나를 거르고, HAVING은 그룹을 만든 뒤 그룹을 걸러요. AVG(score) 같은 집계 결과는 그룹이 생긴 뒤에야 알 수 있어 HAVING에 써요.',
    glossary: [{ term: 'HAVING', meaning: 'GROUP BY로 만든 그룹 중 조건에 맞는 그룹만 남기는 절' }],
    mode: 'executable', datasetId: 'school',
    prompt: '평균 점수가 80 이상인 강좌의 course_id와 평균을 조회하도록 오류를 고치세요.',
    prediction: {
      prompt: '지금 SQL을 실행하면 어떻게 될까요?',
      options: ['정상 실행', 'WHERE에서 집계 함수를 써서 오류', '빈 결과'],
      correctIndex: 1,
      reveal: 'WHERE 단계에는 아직 그룹이 없어서 AVG를 계산할 수 없어요.',
    },
    hints: [
      '집계 함수 조건은 그룹을 만든 다음에 확인해요.',
      'WHERE AVG(score) >= 80 부분을 GROUP BY 뒤의 다른 절로 옮기세요.',
      'GROUP BY course_id HAVING AVG(score) >= 80',
    ],
    solution: { sql: 'SELECT course_id, AVG(score) AS avg_score FROM enrollment GROUP BY course_id HAVING AVG(score) >= 80;', reasoning: 'HAVING이 강좌 그룹의 평균을 보고 걸러요. SQL캠프(평균 90)만 남아요.', commonMistakes: ['HAVING을 GROUP BY 앞에 쓰는 것'] },
    conceptTags: ['HAVING', 'GROUP BY'],
    successMessage: 'HAVING으로 그룹 조건을 걸었어요.',
    config: {
      kind: 'sql-editor',
      starterSql: 'SELECT course_id, AVG(score) AS avg_score\nFROM enrollment\nWHERE AVG(score) >= 80\nGROUP BY course_id;',
      solutionSql: 'SELECT course_id, AVG(score) FROM enrollment GROUP BY course_id HAVING AVG(score) >= 80',
      ordered: false,
    },
  }),
  defineActivity({
    id: 'U06-A04', unitId: 'U06', title: '학과별 평균 SQL 완성',
    objective: 'GROUP BY, 집계, ORDER BY를 조합해 학과별 통계를 만든다.',
    estimatedMinutes: 7,
    explanation: 'GROUP BY 뒤에 쓴 열과 집계 함수만 SELECT에 쓸 수 있어요. 결과를 정렬하려면 맨 끝에 ORDER BY를 써요. ORDER BY에서는 SELECT의 별칭도 쓸 수 있어요.',
    glossary: [{ term: 'ORDER BY', meaning: '결과 행을 정렬하는 절. ASC(오름차순, 기본), DESC(내림차순)' }],
    mode: 'executable', datasetId: 'school',
    prompt: '학과(dept_id)별 학생 수와 평균 학년을 dept_id, 학생 수, 평균 학년 순서의 열로, dept_id 오름차순으로 조회하세요.',
    hints: [
      '학과별 → GROUP BY dept_id',
      '학생 수는 COUNT(*), 평균 학년은 AVG(grade)',
      'SELECT dept_id, COUNT(*), AVG(grade) FROM students GROUP BY dept_id ORDER BY dept_id;',
    ],
    solution: { sql: 'SELECT dept_id, COUNT(*) AS student_count, AVG(grade) AS avg_grade FROM students GROUP BY dept_id ORDER BY dept_id;', reasoning: '학과로 묶어 행 수와 학년 평균을 구하고 dept_id 순으로 정렬해요.', commonMistakes: ['ORDER BY를 빼서 순서가 보장되지 않는 것', 'SELECT에 student_name처럼 그룹에 없는 열을 넣는 것'] },
    conceptTags: ['GROUP BY', 'ORDER BY', '집계 함수'],
    successMessage: '학과별 학생 수와 평균 학년을 계산했어요.',
    config: {
      kind: 'sql-editor',
      starterSql: 'SELECT dept_id\nFROM students\n',
      solutionSql: 'SELECT dept_id, COUNT(*), AVG(grade) FROM students GROUP BY dept_id ORDER BY dept_id',
      ordered: true,
      blocks: ['COUNT(*)', 'AVG(grade)', 'GROUP BY dept_id', 'ORDER BY dept_id'],
    },
  }),
];
