import { defineActivity } from '../define';

export const U07 = [
  defineActivity({
    id: 'U07-A01', unitId: 'U07', title: '같은 키로 두 표 연결',
    objective: 'INNER JOIN이 같은 키 값을 가진 행끼리 짝짓는 과정을 직접 연결한다.',
    estimatedMinutes: 7,
    explanation: 'JOIN은 두 표의 행을 조건(보통 같은 키 값)으로 이어 붙여요. INNER JOIN은 짝이 있는 행만 결과에 남겨요. 학생의 dept_id와 학과의 dept_id가 같으면 한 줄로 이어져요.',
    glossary: [
      { term: 'INNER JOIN', meaning: '양쪽 모두 짝이 있는 행만 남기는 조인' },
      { term: 'ON', meaning: '두 표를 어떤 조건으로 연결할지 쓰는 곳. 예: ON s.dept_id = d.dept_id' },
      { term: '테이블 별칭', meaning: 'students s처럼 표에 붙인 짧은 이름. s.dept_id로 어느 표의 열인지 구분' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '왼쪽 학생을 고른 뒤, 같은 dept_id를 가진 오른쪽 학과를 눌러 모든 짝을 연결하세요.',
    prediction: {
      prompt: '전기에너지(40) 학과는 INNER JOIN 결과에 나올까요?',
      options: ['나온다', '나오지 않는다 — 짝이 되는 학생이 없어서'],
      correctIndex: 1,
      reveal: '40번 학과 학생이 없어 짝이 없으므로 INNER JOIN 결과에서 빠져요.',
    },
    hints: [
      '학생 행의 dept_id 값을 보고, 같은 dept_id인 학과 행을 찾으세요.',
      '학과 하나에 여러 학생이 연결될 수 있어요(1:N).',
      '학생 6명 모두 짝이 있어서 연결선은 6개예요.',
    ],
    solution: { sql: 'SELECT s.student_name, d.dept_name FROM students s INNER JOIN departments d ON s.dept_id = d.dept_id;', reasoning: '학생마다 dept_id가 같은 학과 하나와 짝지어 6쌍이에요. 전기에너지는 짝이 없어요.', commonMistakes: ['학과 하나에 학생 하나만 연결된다고 생각하는 것'] },
    conceptTags: ['INNER JOIN', 'ON'],
    successMessage: 'JOIN으로 두 표를 연결했어요.',
    config: {
      kind: 'join-visualizer',
      leftTitle: 'students', rightTitle: 'departments',
      leftSql: 'SELECT student_id AS id, student_name, dept_id FROM students ORDER BY student_id',
      rightSql: 'SELECT dept_id AS id, dept_id, dept_name FROM departments ORDER BY dept_id',
      pairsSql: 'SELECT s.student_id, d.dept_id FROM students s JOIN departments d ON s.dept_id = d.dept_id',
      keepUnmatchedLeft: false,
      joinSql: 'SELECT s.student_name, d.dept_name\nFROM students s INNER JOIN departments d ON s.dept_id = d.dept_id\nORDER BY s.student_id;',
      altJoinSql: [
        { label: 'USING으로 쓰기', sql: 'SELECT student_name, dept_name\nFROM students JOIN departments USING (dept_id)\nORDER BY student_id;' },
        { label: 'NATURAL JOIN (같은 이름 열 자동 연결)', sql: 'SELECT student_name, dept_name\nFROM students NATURAL JOIN departments\nORDER BY student_id;' },
      ],
    },
  }),
  defineActivity({
    id: 'U07-A02', unitId: 'U07', title: 'INNER와 LEFT 결과 전환',
    objective: 'LEFT JOIN이 짝이 없는 왼쪽 행을 NULL과 함께 남기는 것을 확인한다.',
    estimatedMinutes: 7,
    explanation: 'LEFT (OUTER) JOIN은 왼쪽 표의 모든 행을 남기고, 짝이 없으면 오른쪽 열을 NULL로 채워요. RIGHT JOIN은 반대로 오른쪽을, FULL JOIN은 양쪽을 모두 남겨요. CROSS JOIN은 조건 없이 모든 조합을 만들어요.',
    glossary: [
      { term: 'LEFT JOIN', meaning: '왼쪽 행은 모두 남기고 짝 없는 오른쪽 열은 NULL' },
      { term: 'RIGHT / FULL JOIN', meaning: '오른쪽 모두 / 양쪽 모두 남기는 외부조인' },
      { term: 'CROSS JOIN', meaning: '두 표 행의 모든 조합(곱)' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '학생을 수강 행과 LEFT JOIN으로 연결하세요. 짝이 없는 학생은 "NULL로 남기기"를 누르세요.',
    prediction: {
      prompt: 'students LEFT JOIN enrollment 결과는 몇 행일까요?',
      options: ['6행', '8행', '36행'],
      correctIndex: 1,
      reveal: '수강 6행 + 수강 없는 학생(라온, 마루) 2행 = 8행이에요.',
      verifySql: "SELECT COUNT(*) || '행' FROM students s LEFT JOIN enrollment e ON s.student_id = e.student_id",
    },
    hints: [
      '한 학생이 수강 행 여러 개와 연결될 수 있어요(가온은 2개).',
      '수강 행이 없는 학생은 오른쪽 짝 대신 NULL로 남겨요.',
      '라온(4), 마루(5)는 NULL로 남기고 나머지는 같은 student_id의 수강 행과 연결해요.',
    ],
    solution: { sql: 'SELECT s.student_id, e.course_id, e.score FROM students s LEFT JOIN enrollment e ON s.student_id = e.student_id ORDER BY s.student_id, e.course_id;', reasoning: '짝이 있는 6쌍과 짝 없는 학생 2명이 NULL과 함께 남아 8행이에요.', commonMistakes: ['짝 없는 학생을 빼는 것(INNER JOIN 결과)'] },
    conceptTags: ['LEFT JOIN', '외부조인', 'NULL'],
    dialectNotes: ['RIGHT JOIN과 FULL JOIN은 SQLite 3.39 이상에서 실행돼요. 이 앱의 SQLite 3.49에서 실제로 실행할 수 있어요.', "Oracle의 옛 문법 WHERE s.id = e.id(+)는 SQLite에서 실행되지 않아요."],
    successMessage: 'LEFT JOIN으로 짝 없는 학생까지 남겼어요.',
    config: {
      kind: 'join-visualizer',
      leftTitle: 'students', rightTitle: 'enrollment',
      leftSql: 'SELECT student_id AS id, student_id, student_name FROM students ORDER BY student_id',
      rightSql: "SELECT student_id || '-' || course_id AS id, student_id, course_id, score FROM enrollment ORDER BY student_id, course_id",
      pairsSql: "SELECT s.student_id, CASE WHEN e.student_id IS NULL THEN NULL ELSE e.student_id || '-' || e.course_id END FROM students s LEFT JOIN enrollment e ON s.student_id = e.student_id",
      keepUnmatchedLeft: true,
      joinSql: 'SELECT s.student_id, s.student_name, e.course_id, e.score\nFROM students s LEFT JOIN enrollment e ON s.student_id = e.student_id\nORDER BY s.student_id, e.course_id;',
      altJoinSql: [
        { label: 'INNER JOIN과 비교', sql: 'SELECT s.student_id, s.student_name, e.course_id, e.score\nFROM students s INNER JOIN enrollment e ON s.student_id = e.student_id\nORDER BY s.student_id, e.course_id;' },
        { label: 'RIGHT JOIN (강좌 기준)', sql: 'SELECT e.student_id, c.course_name\nFROM enrollment e RIGHT JOIN courses c ON c.course_id = e.course_id\nORDER BY c.course_id, e.student_id;' },
        { label: 'FULL JOIN (학과·학생 모두)', sql: 'SELECT d.dept_name, s.student_name\nFROM departments d FULL JOIN students s ON s.dept_id = d.dept_id\nORDER BY d.dept_id, s.student_id;' },
        { label: 'CROSS JOIN 행 수', sql: 'SELECT COUNT(*) AS 조합수 FROM students CROSS JOIN courses;' },
      ],
    },
  }),
  defineActivity({
    id: 'U07-A03', unitId: 'U07', title: '다대다 조인과 중복행',
    objective: '중간 테이블을 거친 다중 조인과, 조인으로 값이 반복되는 이유를 이해한다.',
    estimatedMinutes: 7,
    explanation: '학생과 강좌는 다대다(M:N)라서 수강(enrollment) 같은 중간 테이블로 연결해요. 세 표를 조인하면 결과 행 수는 보통 중간 테이블 행 수를 따라가요. 그래서 학과처럼 "1" 쪽 값은 연결된 행마다 반복돼 보여요.',
    glossary: [
      { term: '다대다(M:N)', meaning: '양쪽 모두 여러 개와 연결될 수 있는 관계' },
      { term: '중간 테이블', meaning: 'M:N을 1:N 두 개로 풀어 주는 표. 예: enrollment' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '두 SQL을 실행해 결과 행 수를 확인하고, 학과명이 반복되는 이유를 고르세요.',
    prediction: {
      prompt: '학생-수강-강좌 세 표를 조인한 첫 번째 SQL의 결과는 몇 행일까요?',
      options: ['3행', '6행', '18행'],
      correctIndex: 1,
      reveal: '수강 행 하나가 학생 하나, 강좌 하나와 짝지어지므로 수강 행 수(6)만큼 나와요.',
      verifySql: "SELECT COUNT(*) || '행' FROM students s JOIN enrollment e ON s.student_id = e.student_id JOIN courses c ON c.course_id = e.course_id",
    },
    hints: [
      '두 번째 SQL은 학과 → 학생 → 수강으로 이어져요.',
      'AI컴퓨터 학생은 가온(수강 2개), 나래(1개), 바다(1개)예요.',
      '학과 1행이 학생·수강 행마다 짝지어져 반복돼요. 중복을 줄이려면 DISTINCT나 집계를 써요.',
    ],
    solution: { reasoning: "학과 1행이 연결된 수강 행마다 다시 나와요. 'AI컴퓨터'는 수강 행 4개와 연결돼 4번 보여요.", commonMistakes: ['조인이 데이터를 잘못 복제했다고 생각하는 것'] },
    conceptTags: ['다대다 중간 테이블', '다중 테이블', '중복행'],
    successMessage: '다대다 조인에서 값이 반복되는 이유를 확인했어요.',
    config: {
      kind: 'predict-result',
      sql: 'SELECT s.student_name, c.course_name\nFROM students s\nJOIN enrollment e ON s.student_id = e.student_id\nJOIN courses c ON c.course_id = e.course_id\nORDER BY s.student_id, c.course_id;',
      compareSql: [{ label: '학과명만 조회', sql: 'SELECT d.dept_name\nFROM departments d\nJOIN students s ON s.dept_id = d.dept_id\nJOIN enrollment e ON e.student_id = s.student_id;' }],
      check: {
        prompt: "두 번째 SQL에서 'AI컴퓨터'는 몇 번 나올까요?",
        options: ['1번', '3번', '4번'],
        correctIndex: 2,
        reveal: '가온 2개 + 나래 1개 + 바다 1개 = 수강 행 4개와 연결돼 4번 나와요.',
        verifySql: "SELECT COUNT(*) || '번' FROM departments d JOIN students s ON s.dept_id = d.dept_id JOIN enrollment e ON e.student_id = s.student_id WHERE d.dept_name = 'AI컴퓨터'",
      },
    },
  }),
  defineActivity({
    id: 'U07-A04', unitId: 'U07', title: 'LEFT JOIN의 ON과 WHERE',
    objective: '외부조인에서 조건을 ON에 둘 때와 WHERE에 둘 때의 차이를 고친다.',
    estimatedMinutes: 8,
    explanation: 'LEFT JOIN에서 ON 조건은 "어떤 행과 짝지을지"를 정하고, WHERE는 조인이 끝난 결과에서 행을 걸러요. 오른쪽 표 조건을 WHERE에 쓰면 NULL로 남긴 행이 걸러져 사실상 INNER JOIN이 돼요.',
    glossary: [{ term: '외부조인 조건 위치', meaning: '오른쪽 표 조건은 ON에 두어야 짝 없는 왼쪽 행이 남아요' }],
    mode: 'executable', datasetId: 'school',
    prompt: '모든 학생을 남기고 SQL캠프(101) 점수만 붙이세요. SQL캠프를 듣지 않은 학생도 NULL로 남아야 해요(학번 순).',
    prediction: {
      prompt: '지금 SQL(WHERE e.course_id = 101)의 결과는 몇 행일까요?',
      options: ['3행', '6행', '8행'],
      correctIndex: 0,
      reveal: 'WHERE가 course_id가 NULL이거나 101이 아닌 행을 걸러 SQL캠프 수강생 3명만 남아요.',
      verifySql: "SELECT COUNT(*) || '행' FROM students s LEFT JOIN enrollment e ON s.student_id = e.student_id WHERE e.course_id = 101",
    },
    hints: [
      'WHERE는 조인이 끝난 뒤 행을 걸러요. NULL로 남긴 학생도 여기서 사라져요.',
      'e.course_id = 101 조건을 짝짓는 조건(ON) 쪽으로 옮기세요.',
      'ON s.student_id = e.student_id AND e.course_id = 101',
    ],
    solution: { sql: 'SELECT s.student_id, e.score FROM students s LEFT JOIN enrollment e ON s.student_id = e.student_id AND e.course_id = 101 ORDER BY s.student_id;', reasoning: '조건을 ON으로 옮기면 SQL캠프 행과만 짝짓고, 짝 없는 학생은 NULL로 남아 6행이 돼요.', commonMistakes: ['WHERE e.course_id = 101 OR e.course_id IS NULL로 고치는 것(다른 강좌만 들은 학생 바다가 빠짐)'] },
    conceptTags: ['외부조인 조건 위치', 'LEFT JOIN'],
    successMessage: '외부조인 조건을 ON으로 옮겨 모든 학생을 남겼어요.',
    config: {
      kind: 'sql-editor',
      starterSql: 'SELECT s.student_id, e.score\nFROM students s\nLEFT JOIN enrollment e ON s.student_id = e.student_id\nWHERE e.course_id = 101\nORDER BY s.student_id;',
      solutionSql: 'SELECT s.student_id, e.score FROM students s LEFT JOIN enrollment e ON s.student_id = e.student_id AND e.course_id = 101 ORDER BY s.student_id',
      ordered: true,
    },
  }),
];
