import { defineActivity } from '../define';

export const U08 = [
  defineActivity({
    id: 'U08-A01', unitId: 'U08', title: '서브쿼리 결과를 조건에 넣기',
    objective: '단일행 서브쿼리의 결과를 바깥 쿼리의 비교 조건으로 쓴다.',
    estimatedMinutes: 6,
    explanation: '서브쿼리는 괄호 안에 넣은 또 하나의 SELECT예요. 값 하나를 돌려주는 단일행 서브쿼리는 =, > 같은 비교에 바로 쓸 수 있어요. 안쪽을 먼저 실행해 보면 바깥 조건이 무엇과 비교하는지 알 수 있어요.',
    glossary: [
      { term: '서브쿼리', meaning: 'SQL 안에 괄호로 넣은 SELECT 문' },
      { term: '단일행 서브쿼리', meaning: '결과가 한 행(값 하나)인 서브쿼리. 비교 연산자와 함께 써요' },
      { term: '스칼라 서브쿼리', meaning: 'SELECT 절 등에서 값 하나처럼 쓰이는 서브쿼리' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '전체 평균 점수보다 높은 점수를 받은 수강 행의 student_id, course_id, score를 조회하세요. 평균값을 직접 쓰지 말고 서브쿼리로 구하세요.',
    prediction: {
      prompt: '안쪽 SELECT AVG(score) FROM enrollment 의 결과는?',
      options: ['68.3', '82', '85'],
      correctIndex: 1,
      reveal: 'NULL을 뺀 5개 점수의 평균이 82예요.',
      verifySql: 'SELECT AVG(score) FROM enrollment',
    },
    hints: [
      '먼저 탐색 버튼으로 평균을 구하는 안쪽 쿼리를 실행해 보세요.',
      'WHERE score > ( 평균을 구하는 SELECT ) 형태예요.',
      'WHERE score > (SELECT AVG(score) FROM enrollment)',
    ],
    solution: { sql: 'SELECT student_id, course_id, score FROM enrollment WHERE score > (SELECT AVG(score) FROM enrollment);', reasoning: '안쪽에서 82를 구하고 바깥에서 82보다 큰 90점 두 행을 남겨요.', commonMistakes: ['82를 숫자로 직접 써서 데이터가 바뀌면 틀리는 것', 'WHERE score > AVG(score)로 쓰는 것'] },
    conceptTags: ['단일행 서브쿼리', '서브쿼리'],
    successMessage: '서브쿼리 결과를 바깥 조건에 넣었어요.',
    config: {
      kind: 'sql-editor',
      starterSql: 'SELECT student_id, course_id, score\nFROM enrollment\nWHERE score > ( );',
      solutionSql: 'SELECT student_id, course_id, score FROM enrollment WHERE score > (SELECT AVG(score) FROM enrollment)',
      ordered: false,
      explore: [{ label: '안쪽 쿼리만 실행', sql: 'SELECT AVG(score) FROM enrollment;' }],
    },
  }),
  defineActivity({
    id: 'U08-A02', unitId: 'U08', title: 'EXISTS를 학생별로 실행',
    objective: '상관 서브쿼리가 바깥 행마다 다시 평가되는 과정을 따라간다.',
    estimatedMinutes: 6,
    explanation: '상관 서브쿼리는 바깥 쿼리의 값을 받아 행마다 다시 실행돼요. EXISTS (서브쿼리)는 서브쿼리 결과가 한 행이라도 있으면 TRUE예요. 학생 한 명씩 "이 학생의 IoT캠프 수강 행이 있나?"를 확인해 봐요.',
    glossary: [
      { term: '상관 서브쿼리', meaning: '바깥 행의 값(s.student_id)을 사용해 행마다 다시 실행되는 서브쿼리' },
      { term: 'EXISTS', meaning: '서브쿼리 결과 행이 하나라도 있으면 TRUE' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: 'EXISTS (SELECT 1 FROM enrollment e WHERE e.student_id = s.student_id AND e.course_id = 102)가 학생마다 TRUE인지 FALSE인지 고르세요.',
    hints: [
      '학생마다 enrollment에서 그 학생의 102번 강좌 행을 찾아보세요.',
      '한 행이라도 있으면 TRUE, 없으면 FALSE예요.',
      'IoT캠프(102)를 들은 학생은 가온(1), 다온(3), 바다(6)예요.',
    ],
    solution: { sql: 'SELECT s.student_id FROM students s WHERE EXISTS (SELECT 1 FROM enrollment e WHERE e.student_id = s.student_id AND e.course_id = 102);', reasoning: '1, 3, 6번 학생은 102 수강 행이 있어 TRUE, 나머지는 FALSE예요.', commonMistakes: ['다른 강좌를 들은 나래(2)를 TRUE로 고르는 것'] },
    conceptTags: ['상관 서브쿼리', 'EXISTS'],
    successMessage: 'EXISTS가 학생마다 평가되는 과정을 따라갔어요.',
    config: {
      kind: 'classify', layout: 'bins',
      items: [
        { id: '1', label: '1 가온' }, { id: '2', label: '2 나래' }, { id: '3', label: '3 다온' },
        { id: '4', label: '4 라온' }, { id: '5', label: '5 마루' }, { id: '6', label: '6 바다' },
      ],
      options: [{ id: 'T', label: 'TRUE (남음)' }, { id: 'F', label: 'FALSE (빠짐)' }],
      answer: { source: 'sql', sql: "SELECT CAST(s.student_id AS TEXT), CASE WHEN EXISTS (SELECT 1 FROM enrollment e WHERE e.student_id = s.student_id AND e.course_id = 102) THEN 'T' ELSE 'F' END FROM students s" },
      demoSql: 'SELECT s.student_id, s.student_name\nFROM students s\nWHERE EXISTS (SELECT 1 FROM enrollment e\n              WHERE e.student_id = s.student_id AND e.course_id = 102);',
    },
  }),
  defineActivity({
    id: 'U08-A03', unitId: 'U08', title: 'UNION과 UNION ALL',
    objective: '집합 연산자의 중복 처리 차이를 비교한다.',
    estimatedMinutes: 6,
    explanation: '집합 연산자는 두 SELECT 결과를 위아래로 합치거나 빼요. UNION은 중복을 없애고, UNION ALL은 그대로 모두 남겨요. INTERSECT는 양쪽 공통 행, EXCEPT(Oracle은 MINUS)는 왼쪽에만 있는 행이에요. 양쪽 열 개수가 같아야 해요.',
    glossary: [
      { term: 'UNION / UNION ALL', meaning: '합집합(중복 제거) / 단순 합치기(중복 유지)' },
      { term: 'INTERSECT', meaning: '양쪽 모두에 있는 행' },
      { term: 'EXCEPT (MINUS)', meaning: '왼쪽에만 있는 행. Oracle에서는 MINUS' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: 'SQL캠프(101)와 IoT캠프(102) 수강생 번호를 합친 결과들을 실행해 비교하고 질문에 답하세요.',
    prediction: {
      prompt: '101 수강생 UNION 102 수강생의 결과는 몇 행일까요?',
      options: ['4행', '6행', '2행'],
      correctIndex: 0,
      reveal: '101은 {1,2,3}, 102는 {1,3,6}이에요. 중복(1, 3)을 없애면 {1,2,3,6} 4행이에요.',
      verifySql: "SELECT COUNT(*) || '행' FROM (SELECT student_id FROM enrollment WHERE course_id = 101 UNION SELECT student_id FROM enrollment WHERE course_id = 102)",
    },
    hints: [
      '두 강좌를 모두 들은 학생이 중복의 원인이에요.',
      'INTERSECT는 양쪽 목록에 모두 있는 번호만 남겨요.',
      '{1,2,3} ∩ {1,3,6}',
    ],
    solution: { reasoning: 'UNION은 4행, UNION ALL은 6행이에요. INTERSECT는 두 강좌를 모두 들은 1, 3번이에요.', commonMistakes: ['UNION도 중복을 남긴다고 생각하는 것'] },
    conceptTags: ['UNION/UNION ALL', 'INTERSECT', 'EXCEPT(MINUS)'],
    dialectNotes: ['Oracle은 EXCEPT 대신 MINUS를 써요. SQLite·SQL Server는 EXCEPT를 써요.'],
    successMessage: 'UNION과 UNION ALL의 중복 차이를 확인했어요.',
    config: {
      kind: 'predict-result',
      sql: 'SELECT student_id FROM enrollment WHERE course_id = 101\nUNION\nSELECT student_id FROM enrollment WHERE course_id = 102;',
      compareSql: [
        { label: 'UNION ALL', sql: 'SELECT student_id FROM enrollment WHERE course_id = 101\nUNION ALL\nSELECT student_id FROM enrollment WHERE course_id = 102;' },
        { label: 'INTERSECT', sql: 'SELECT student_id FROM enrollment WHERE course_id = 101\nINTERSECT\nSELECT student_id FROM enrollment WHERE course_id = 102;' },
        { label: 'EXCEPT (Oracle MINUS)', sql: 'SELECT student_id FROM enrollment WHERE course_id = 101\nEXCEPT\nSELECT student_id FROM enrollment WHERE course_id = 102;' },
      ],
      check: {
        prompt: 'INTERSECT 결과는 무엇일까요?',
        options: ['1, 3', '2', '1, 2, 3, 6', '6'],
        correctIndex: 0,
        reveal: '두 강좌를 모두 수강한 가온(1)과 다온(3)이에요.',
        verifySql: "SELECT GROUP_CONCAT(student_id, ', ') FROM (SELECT student_id FROM enrollment WHERE course_id = 101 INTERSECT SELECT student_id FROM enrollment WHERE course_id = 102 ORDER BY 1)",
      },
    },
  }),
  defineActivity({
    id: 'U08-A04', unitId: 'U08', title: 'IN·NOT IN·ANY·ALL 예측',
    objective: '다중행 서브쿼리 연산자가 몇 행을 남기는지 예측한다.',
    estimatedMinutes: 7,
    explanation: '여러 행을 돌려주는 서브쿼리에는 IN, NOT IN, ANY, ALL을 써요. > ANY는 "목록 중 하나보다라도 크면", < ALL은 "목록의 모든 값보다 작으면" 참이에요. SQLite에는 ANY/ALL이 없어 MIN/MAX로 바꾼 같은 의미의 식으로 계산해요.',
    glossary: [
      { term: '다중행 서브쿼리', meaning: '여러 행을 돌려주는 서브쿼리. IN, ANY, ALL, EXISTS와 함께 써요' },
      { term: '> ANY', meaning: '서브쿼리 값 중 하나보다라도 크면 참 (= 최솟값보다 크면)' },
      { term: '< ALL', meaning: '서브쿼리의 모든 값보다 작으면 참 (= 최솟값보다 작으면)' },
    ],
    mode: 'simulation', datasetId: 'school',
    prompt: '각 조건으로 students를 거르면 몇 명이 남는지 고르세요. AI컴퓨터(10) 학생들의 학년은 3, 3, 2예요.',
    hints: [
      'IN (SELECT student_id FROM enrollment)은 수강 기록이 있는 학생이에요.',
      '> ANY (3, 3, 2)는 2보다 크면 참, < ALL (3, 3, 2)는 2보다 작으면 참이에요.',
      '학년 3인 학생은 3명, 학년 1인 학생은 1명이에요.',
    ],
    solution: { reasoning: 'IN 4명(1,2,3,6), NOT IN 2명(4,5), > ANY는 학년 3인 3명, < ALL은 학년 1인 1명이에요. ANY/ALL은 SQLite에서 MIN 비교로 같은 결과를 계산했어요.', commonMistakes: ['> ANY를 "모든 값보다 크다"로 생각하는 것'] },
    conceptTags: ['IN/EXISTS/ANY/ALL', '다중행 서브쿼리'],
    dialectNotes: ['ANY/ALL은 Oracle·SQL Server에서 실행돼요. SQLite에서는 > ANY(목록) → > (SELECT MIN(...)), < ALL(목록) → < (SELECT MIN(...))처럼 바꿔 계산했어요(목록에 NULL이 없고 비어 있지 않을 때 같은 결과).'],
    successMessage: '다중행 서브쿼리 연산자의 결과를 예측했어요.',
    config: {
      kind: 'classify', layout: 'bins',
      items: [
        { id: 'i1', label: 'student_id IN (SELECT student_id FROM enrollment)' },
        { id: 'i2', label: 'student_id NOT IN (SELECT student_id FROM enrollment)' },
        { id: 'i3', label: 'grade > ANY (SELECT grade FROM students WHERE dept_id = 10)' },
        { id: 'i4', label: 'grade < ALL (SELECT grade FROM students WHERE dept_id = 10)' },
      ],
      options: ['0명', '1명', '2명', '3명', '4명'].map((v) => ({ id: v, label: v })),
      answer: { source: 'sql', sql: "SELECT 'i1', COUNT(*) || '명' FROM students WHERE student_id IN (SELECT student_id FROM enrollment) UNION ALL SELECT 'i2', COUNT(*) || '명' FROM students WHERE student_id NOT IN (SELECT student_id FROM enrollment) UNION ALL SELECT 'i3', COUNT(*) || '명' FROM students WHERE grade > (SELECT MIN(grade) FROM students WHERE dept_id = 10) UNION ALL SELECT 'i4', COUNT(*) || '명' FROM students WHERE grade < (SELECT MIN(grade) FROM students WHERE dept_id = 10)" },
      demoSql: '-- ANY/ALL을 SQLite에서 같은 의미로 바꾼 식\nSELECT student_id, student_name, grade FROM students\nWHERE grade > (SELECT MIN(grade) FROM students WHERE dept_id = 10);',
    },
  }),
];
