import { defineActivity } from '../define';

export const U09 = [
  defineActivity({
    id: 'U09-A01', unitId: 'U09', title: '동점 순위 번호 붙이기',
    objective: 'RANK와 DENSE_RANK가 동점을 처리하는 방식을 직접 매긴다.',
    estimatedMinutes: 7,
    explanation: '윈도우 함수는 행을 줄이지 않고 각 행 옆에 계산 값을 붙여요. RANK는 동점에 같은 순위를 주고 다음 순위를 건너뛰어요(1,1,3). DENSE_RANK는 건너뛰지 않아요(1,1,2). ROW_NUMBER는 동점이어도 1,2,3처럼 모두 다른 번호예요.',
    glossary: [
      { term: '윈도우 함수', meaning: '행을 묶지 않고 각 행에 순위·누적 값 등을 붙이는 함수. OVER(…)와 함께 써요' },
      { term: 'RANK / DENSE_RANK / ROW_NUMBER', meaning: '동점 같은 순위+건너뜀 / 같은 순위+연속 / 항상 다른 번호' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '점수가 있는 수강 행에 점수 높은 순 RANK와 DENSE_RANK 값을 적으세요.',
    prediction: {
      prompt: '점수 90, 90, 80, 80, 70에 RANK를 매기면 70의 순위는?',
      options: ['3', '5', '4'],
      correctIndex: 1,
      reveal: '앞에 4개 행이 있으므로 RANK는 5예요. DENSE_RANK라면 3이에요.',
    },
    hints: [
      '같은 점수는 같은 순위예요.',
      'RANK는 "나보다 점수가 높은 행 수 + 1"이에요.',
      'DENSE_RANK는 "나보다 높은 서로 다른 점수 개수 + 1"이에요.',
    ],
    solution: { sql: 'SELECT student_id, course_id, score, RANK() OVER (ORDER BY score DESC) AS r, DENSE_RANK() OVER (ORDER BY score DESC) AS dr FROM enrollment WHERE score IS NOT NULL;', reasoning: '90점 두 행은 1위, 80점 두 행은 RANK 3·DENSE_RANK 2, 70점은 RANK 5·DENSE_RANK 3이에요.', commonMistakes: ['RANK에서 80점을 2위로 적는 것'] },
    conceptTags: ['RANK/DENSE_RANK/ROW_NUMBER', 'OVER'],
    successMessage: 'RANK와 DENSE_RANK로 동점 순위를 매겼어요.',
    config: {
      kind: 'window-visualizer',
      rowsSql: "SELECT student_id || '-' || course_id AS row_id, student_id, course_id, score FROM enrollment WHERE score IS NOT NULL ORDER BY score DESC, student_id, course_id",
      answerSql: "SELECT student_id || '-' || course_id AS row_id, RANK() OVER (ORDER BY score DESC) AS \"RANK\", DENSE_RANK() OVER (ORDER BY score DESC) AS \"DENSE_RANK\" FROM enrollment WHERE score IS NOT NULL",
      windowSql: 'SELECT student_id, course_id, score,\n  RANK() OVER (ORDER BY score DESC) AS r,\n  DENSE_RANK() OVER (ORDER BY score DESC) AS dr,\n  ROW_NUMBER() OVER (ORDER BY score DESC, student_id, course_id) AS rn\nFROM enrollment WHERE score IS NOT NULL\nORDER BY score DESC, student_id, course_id;',
    },
  }),
  defineActivity({
    id: 'U09-A02', unitId: 'U09', title: 'PARTITION BY로 학과별 순위',
    objective: 'PARTITION BY가 순위를 그룹마다 다시 시작하게 하는 것을 본다.',
    estimatedMinutes: 7,
    explanation: 'OVER 안의 PARTITION BY는 행을 구역으로 나누고, 구역마다 순위를 1부터 다시 매겨요. GROUP BY와 달리 행 수는 그대로예요. ORDER BY는 구역 안에서의 순서를 정해요.',
    glossary: [{ term: 'PARTITION BY', meaning: '윈도우 함수를 계산할 구역을 나눔. 행은 줄지 않아요' }],
    mode: 'executable', datasetId: 'school',
    prompt: '학과 안에서 학년이 높은 순으로 순위가 매겨지도록 OVER 안의 구역 설정을 고르세요.',
    prediction: {
      prompt: 'PARTITION BY dept_id를 넣으면 순위가 1인 학생은 모두 몇 명일까요?',
      options: ['1명', '3명', '4명'],
      correctIndex: 2,
      reveal: '학과 10은 3학년 2명이 공동 1위, 학과 20과 30은 1명씩 1위라 모두 4명이에요.',
      verifySql: "SELECT COUNT(*) || '명' FROM (SELECT RANK() OVER (PARTITION BY dept_id ORDER BY grade DESC) AS r FROM students) WHERE r = 1",
    },
    hints: [
      '"학과 안에서"는 학과마다 구역을 나눈다는 뜻이에요.',
      'PARTITION BY 뒤에 구역을 나눌 열을 써요.',
      'RANK() OVER (PARTITION BY dept_id ORDER BY grade DESC)',
    ],
    solution: { sql: 'SELECT student_id, dept_id, grade, RANK() OVER (PARTITION BY dept_id ORDER BY grade DESC) AS rnk FROM students ORDER BY dept_id, rnk, student_id;', reasoning: '학과별로 구역을 나눠 각 학과 안에서 1위부터 다시 매겨요.', commonMistakes: ['PARTITION BY grade로 학년마다 나누는 것'] },
    conceptTags: ['PARTITION BY', 'OVER'],
    successMessage: 'PARTITION BY로 학과마다 순위를 매겼어요.',
    config: {
      kind: 'row-filter',
      baseSql: 'SELECT student_id, dept_id, grade FROM students',
      template: 'SELECT student_id, dept_id, grade, RANK() OVER ({part} ORDER BY grade DESC) AS rnk FROM students ORDER BY dept_id, rnk, student_id',
      slots: [{ id: 'part', label: '구역 설정', options: [{ label: '(구역 없음)', value: '' }, { label: 'PARTITION BY dept_id', value: 'PARTITION BY dept_id' }, { label: 'PARTITION BY grade', value: 'PARTITION BY grade' }] }],
      solutionSql: 'SELECT student_id, dept_id, grade, RANK() OVER (PARTITION BY dept_id ORDER BY grade DESC) AS rnk FROM students ORDER BY dept_id, rnk, student_id',
      ordered: true,
    },
  }),
  defineActivity({
    id: 'U09-A03', unitId: 'U09', title: 'LAG·LEAD와 누적합',
    objective: '누적 SUM과 프레임(ROWS/RANGE), LAG/LEAD를 실행해 본다.',
    estimatedMinutes: 8,
    explanation: 'SUM(points) OVER (PARTITION BY student_id ORDER BY …)는 학생마다 위에서부터 더해 가는 누적합이에요. ORDER BY만 쓰면 기본 프레임이 RANGE라서 같은 날짜 행은 한꺼번에 더해져요. ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW는 한 행씩 더해요. LAG/LEAD는 이전/다음 행 값을 가져와요.',
    glossary: [
      { term: '누적 집계', meaning: '정렬 순서대로 처음부터 현재 행까지 더해 가는 값' },
      { term: 'ROWS / RANGE', meaning: '프레임을 행 개수로 / 정렬 값의 범위로 정함' },
      { term: 'LAG / LEAD', meaning: '이전 / 다음 행의 값을 가져오는 함수' },
    ],
    mode: 'executable', datasetId: 'points',
    prompt: '학생별로 event_date 순(같은 날짜는 event_id 순)으로 한 행씩 누적한 포인트를 student_id, event_id, points, 누적 열로 조회하고 student_id, event_id 순으로 정렬하세요.',
    prediction: {
      prompt: '가온(1)은 3월 2일에 10점, 5점, 3월 3일에 20점을 받았어요. ORDER BY event_date만 쓴 기본(RANGE) 누적합에서 첫 행(10점)의 누적 값은?',
      options: ['10', '15', '35'],
      correctIndex: 1,
      reveal: 'RANGE는 같은 날짜(3월 2일) 행을 한꺼번에 더해 첫 행부터 15가 돼요.',
      verifySql: 'SELECT c FROM (SELECT event_id, SUM(points) OVER (PARTITION BY student_id ORDER BY event_date) AS c FROM point_events) WHERE event_id = 1',
    },
    hints: [
      '학생마다 따로 누적하려면 PARTITION BY student_id가 필요해요.',
      '같은 날짜도 한 행씩 더하려면 정렬에 event_id를 추가하거나 ROWS 프레임을 쓰세요.',
      'SUM(points) OVER (PARTITION BY student_id ORDER BY event_date, event_id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)',
    ],
    solution: { sql: 'SELECT student_id, event_id, points, SUM(points) OVER (PARTITION BY student_id ORDER BY event_date, event_id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS 누적 FROM point_events ORDER BY student_id, event_id;', reasoning: '학생마다 날짜·이벤트 순으로 한 행씩 더해요. 가온은 10 → 15 → 35예요.', commonMistakes: ['PARTITION BY를 빼서 모든 학생을 이어서 더하는 것', 'ORDER BY event_date만 써서 같은 날짜가 한꺼번에 더해지는 것'] },
    conceptTags: ['누적 집계', 'ROWS/RANGE', 'LAG/LEAD'],
    successMessage: '프레임을 지정해 누적합을 만들었어요.',
    config: {
      kind: 'sql-editor',
      starterSql: 'SELECT student_id, event_id, points,\n  SUM(points) OVER (\n    PARTITION BY student_id\n    ORDER BY event_date\n  ) AS 누적\nFROM point_events\nORDER BY student_id, event_id;',
      solutionSql: 'SELECT student_id, event_id, points, SUM(points) OVER (PARTITION BY student_id ORDER BY event_date, event_id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) FROM point_events ORDER BY student_id, event_id',
      ordered: true,
      explore: [
        { label: 'LAG/LEAD 보기', sql: 'SELECT student_id, event_id, points,\n  LAG(points) OVER (PARTITION BY student_id ORDER BY event_id) AS 이전,\n  LEAD(points) OVER (PARTITION BY student_id ORDER BY event_id) AS 다음\nFROM point_events ORDER BY student_id, event_id;' },
        { label: 'RANGE 기본 프레임 비교', sql: 'SELECT student_id, event_date, points,\n  SUM(points) OVER (PARTITION BY student_id ORDER BY event_date) AS range_누적,\n  SUM(points) OVER (PARTITION BY student_id ORDER BY event_date ROWS UNBOUNDED PRECEDING) AS rows_누적\nFROM point_events ORDER BY student_id, event_id;' },
      ],
    },
  }),
  defineActivity({
    id: 'U09-A04', unitId: 'U09', title: '상위 N과 동점 포함',
    objective: 'Top N에서 RANK와 ROW_NUMBER가 동점을 포함하는지 비교한다.',
    estimatedMinutes: 7,
    explanation: '상위 N개를 고를 때 RANK() <= N은 동점을 모두 포함해서 N개보다 많을 수 있어요. ROW_NUMBER() <= N은 정확히 N개만 남겨요. 윈도우 함수 결과는 WHERE에서 바로 못 쓰므로 인라인 뷰(FROM 안의 서브쿼리)로 감싸요.',
    glossary: [
      { term: 'Top N 쿼리', meaning: '정렬 기준 상위 N개 행을 고르는 쿼리' },
      { term: '인라인 뷰', meaning: 'FROM 절 안의 서브쿼리. 임시 표처럼 써요' },
    ],
    mode: 'executable', datasetId: 'school',
    prompt: '세 가지 Top 3 쿼리를 실행해 행 수를 비교하고 질문에 답하세요.',
    prediction: {
      prompt: 'RANK() <= 3 조건의 결과는 몇 행일까요? (점수 90, 90, 80, 80, 70)',
      options: ['3행', '4행', '5행'],
      correctIndex: 1,
      reveal: '90점 둘(1위), 80점 둘(3위)이 모두 3위 이내라 4행이에요.',
      verifySql: "SELECT COUNT(*) || '행' FROM (SELECT RANK() OVER (ORDER BY score DESC) AS r FROM enrollment WHERE score IS NOT NULL) WHERE r <= 3",
    },
    hints: [
      'RANK는 동점에 같은 순위를 줘요.',
      'ROW_NUMBER는 동점이어도 다른 번호를 줘요.',
      '동점 중 누가 3번이 될지는 ROW_NUMBER의 정렬 기준이 정해요.',
    ],
    solution: { reasoning: 'RANK <= 3은 동점 포함 4행, ROW_NUMBER <= 3과 LIMIT 3은 정확히 3행이에요.', commonMistakes: ['Top N이 항상 N행이라고 생각하는 것'] },
    conceptTags: ['Top N', 'RANK/DENSE_RANK/ROW_NUMBER', '인라인 뷰'],
    dialectNotes: ['Oracle은 ROWNUM 또는 FETCH FIRST 3 ROWS WITH TIES, SQL Server는 TOP (3) WITH TIES를 써요. SQLite는 LIMIT를 써요.', 'NULL의 정렬 위치는 DBMS마다 달라요. SQLite에서 DESC 정렬 시 NULL은 맨 뒤, Oracle에서는 맨 앞이에요.'],
    successMessage: 'Top N에서 동점 포함 여부를 비교했어요.',
    config: {
      kind: 'predict-result',
      sql: 'SELECT student_id, course_id, score, r\nFROM (SELECT e.*, RANK() OVER (ORDER BY score DESC) AS r\n      FROM enrollment e WHERE score IS NOT NULL)\nWHERE r <= 3;',
      compareSql: [
        { label: 'ROW_NUMBER() <= 3', sql: 'SELECT student_id, course_id, score, rn\nFROM (SELECT e.*, ROW_NUMBER() OVER (ORDER BY score DESC, student_id, course_id) AS rn\n      FROM enrollment e WHERE score IS NOT NULL)\nWHERE rn <= 3;' },
        { label: 'ORDER BY … LIMIT 3', sql: 'SELECT student_id, course_id, score FROM enrollment\nWHERE score IS NOT NULL\nORDER BY score DESC, student_id, course_id LIMIT 3;' },
      ],
      check: {
        prompt: 'ROW_NUMBER() <= 3이 80점 학생 중 한 명만 남기는 이유는?',
        options: ['ROW_NUMBER는 동점이어도 서로 다른 번호를 붙이기 때문', '80점 학생 한 명의 점수가 NULL이라서', 'LIMIT가 자동으로 붙어서'],
        correctIndex: 0,
        reveal: '동점 80점 두 행은 3번, 4번을 받아 3번만 남아요. 누가 3번인지는 정렬 기준(student_id)이 정해요.',
      },
    },
  }),
];
