import { defineActivity } from '../define';

const STATE = 'SELECT signup_id, student_id, camp_name, status FROM camp_signup ORDER BY signup_id';

export const U11 = [
  defineActivity({
    id: 'U11-A01', unitId: 'U11', title: '샌드박스에서 UPDATE 전후 비교',
    objective: 'UPDATE가 조건에 맞는 행만 바꾸고 영향 행 수를 확인한다.',
    estimatedMinutes: 6,
    explanation: 'DML(INSERT, UPDATE, DELETE)은 표의 데이터를 바꿔요. UPDATE 표 SET 열 = 값 WHERE 조건은 조건에 맞는 행만 바꾸고, WHERE를 빼면 모든 행이 바뀌어요. 이 활동은 연습용 샌드박스라 실행할 때마다 처음 데이터에서 시작해요.',
    glossary: [
      { term: 'DML', meaning: '데이터를 넣고(INSERT) 바꾸고(UPDATE) 지우는(DELETE) 명령. MERGE도 포함' },
      { term: '영향 행 수', meaning: 'DML이 실제로 바꾼 행의 개수' },
      { term: 'MERGE', meaning: '있으면 UPDATE, 없으면 INSERT를 한 문장으로 하는 명령(Oracle 등)' },
    ],
    mode: 'executable', datasetId: 'sandbox',
    prompt: "camp_signup에서 status가 '신청'인 행을 모두 '확정'으로 바꾸세요. 먼저 탐색으로 바꾸기 전 상태를 보세요.",
    prediction: {
      prompt: '이 UPDATE의 영향 행 수는 몇 개일까요?',
      options: ['1개', '2개', '4개'],
      correctIndex: 1,
      reveal: "'신청' 상태는 나래(SQL캠프)와 다온(IoT캠프) 2행이에요.",
      verifySql: "SELECT COUNT(*) || '개' FROM camp_signup WHERE status = '신청'",
    },
    hints: [
      'UPDATE 표 SET 열 = 새 값 WHERE 조건 형식이에요.',
      "바꿀 행의 조건은 status = '신청'이에요.",
      "UPDATE camp_signup SET status = '확정' WHERE status = '신청';",
    ],
    solution: { sql: "UPDATE camp_signup SET status = '확정' WHERE status = '신청';", reasoning: "WHERE로 '신청' 행만 골라 2행을 '확정'으로 바꿔요. '취소' 행은 그대로예요.", commonMistakes: ["WHERE를 빼서 '취소' 행까지 '확정'이 되는 것"] },
    conceptTags: ['INSERT/UPDATE/DELETE/MERGE', 'DML'],
    dialectNotes: ['MERGE INTO … USING … WHEN MATCHED THEN UPDATE … WHEN NOT MATCHED THEN INSERT는 Oracle·SQL Server 문법이에요. SQLite는 INSERT … ON CONFLICT DO UPDATE로 비슷한 일을 해요.'],
    successMessage: "UPDATE로 '신청' 행만 '확정'으로 바꿨어요.",
    config: {
      kind: 'sql-editor',
      starterSql: 'UPDATE camp_signup\nSET status = \nWHERE ;',
      solutionSql: "UPDATE camp_signup SET status = '확정' WHERE status = '신청'",
      ordered: true,
      allow: ['update', 'select'],
      stateCheckSql: STATE,
      explore: [{ label: '바꾸기 전 상태', sql: `${STATE};` }],
    },
  }),
  defineActivity({
    id: 'U11-A02', unitId: 'U11', title: 'COMMIT·ROLLBACK·SAVEPOINT',
    objective: '트랜잭션 제어 명령으로 원하는 변경만 확정한다.',
    estimatedMinutes: 7,
    explanation: '트랜잭션은 BEGIN으로 시작해 COMMIT(확정) 또는 ROLLBACK(전체 취소)으로 끝나요. SAVEPOINT는 중간 저장점이고, ROLLBACK TO 저장점은 그 뒤의 변경만 취소해요. 지금은 실수로 가온의 신청을 취소한 UPDATE까지 실행된 상태예요.',
    glossary: [
      { term: 'TCL', meaning: 'COMMIT, ROLLBACK, SAVEPOINT처럼 트랜잭션을 제어하는 명령' },
      { term: 'SAVEPOINT', meaning: '트랜잭션 안의 중간 저장점' },
      { term: 'ROLLBACK TO', meaning: '지정한 저장점 이후의 변경만 취소' },
    ],
    mode: 'executable', datasetId: 'sandbox',
    prompt: '라온의 AI캠프 신청(INSERT)은 남기고, 가온을 취소한 UPDATE만 되돌린 뒤 트랜잭션을 확정하세요. 실수하면 "처음 상태로"를 누르세요.',
    prediction: {
      prompt: '지금 ROLLBACK(저장점 없이)을 누르면 라온의 신청은 어떻게 될까요?',
      options: ['남는다', '함께 취소된다'],
      correctIndex: 1,
      reveal: 'ROLLBACK은 BEGIN 이후 모든 변경을 취소해서 라온의 INSERT도 사라져요.',
    },
    hints: [
      '실행 기록: BEGIN → INSERT(라온) → SAVEPOINT sp1 → UPDATE(가온 취소)',
      'sp1 이후의 변경만 되돌리는 명령이 있어요.',
      'ROLLBACK TO sp1 → COMMIT',
    ],
    solution: { sql: 'ROLLBACK TO sp1;\nCOMMIT;', reasoning: 'ROLLBACK TO sp1이 UPDATE만 취소하고, COMMIT이 라온의 INSERT를 확정해요.', commonMistakes: ['ROLLBACK으로 INSERT까지 취소하는 것', 'RELEASE sp1 후 COMMIT으로 UPDATE까지 확정하는 것'] },
    conceptTags: ['COMMIT/ROLLBACK/SAVEPOINT', 'TCL'],
    dialectNotes: ['Oracle은 DML을 실행하면 자동으로 트랜잭션이 시작되고 BEGIN을 쓰지 않아요. SQL Server는 BEGIN TRAN, SAVE TRAN을 써요.'],
    successMessage: 'SAVEPOINT로 원하는 변경만 확정했어요.',
    config: {
      kind: 'transaction',
      initialLog: [
        'BEGIN',
        "INSERT INTO camp_signup(student_id, camp_name, status) VALUES (4, 'AI캠프', '신청')",
        'SAVEPOINT sp1',
        "UPDATE camp_signup SET status = '취소' WHERE student_id = 1",
      ],
      actions: [
        { id: 'rollback_to', label: 'ROLLBACK TO sp1', sql: 'ROLLBACK TO sp1' },
        { id: 'release', label: 'RELEASE sp1', sql: 'RELEASE sp1' },
        { id: 'commit', label: 'COMMIT', sql: 'COMMIT' },
        { id: 'rollback', label: 'ROLLBACK', sql: 'ROLLBACK' },
      ],
      stateSql: STATE,
      solutionActions: ['ROLLBACK TO sp1', 'COMMIT'],
      requireClosed: true,
    },
  }),
  defineActivity({
    id: 'U11-A03', unitId: 'U11', title: '제약조건 위반 고치기',
    objective: 'FOREIGN KEY와 CHECK 위반 오류를 읽고 INSERT를 고친다.',
    estimatedMinutes: 6,
    explanation: '제약조건은 잘못된 데이터가 들어오지 않게 막는 규칙이에요. NOT NULL, UNIQUE, PRIMARY KEY, FOREIGN KEY, CHECK가 있어요. 오류 메시지가 어떤 제약을 어겼는지 알려주니, 그 열의 허용 값을 확인해 고치면 돼요.',
    glossary: [
      { term: 'DDL', meaning: 'CREATE, ALTER, DROP, TRUNCATE처럼 표의 구조를 정하는 명령' },
      { term: '제약조건', meaning: '열에 들어갈 값을 제한하는 규칙. 예: CHECK(status IN (…))' },
    ],
    mode: 'executable', datasetId: 'sandbox',
    prompt: "마루(student_id 5)를 SQL캠프에 '신청' 상태로 추가하려 해요. 지금 INSERT의 오류를 읽고 고쳐 실행하세요.",
    prediction: {
      prompt: '지금 INSERT에서 문제가 되는 값은 무엇일까요?',
      options: ["student_id 9와 status '대기'", "camp_name 'SQL캠프'", '문제가 없다'],
      correctIndex: 0,
      reveal: "학생 9는 students에 없고(FK), '대기'는 CHECK(신청/확정/취소)에 없어요.",
    },
    hints: [
      '오류 메시지에서 어떤 제약조건인지 읽어 보세요.',
      "student_id는 students에 있는 번호, status는 '신청', '확정', '취소' 중 하나예요.",
      "VALUES (5, 'SQL캠프', '신청')",
    ],
    solution: { sql: "INSERT INTO camp_signup(student_id, camp_name, status) VALUES (5, 'SQL캠프', '신청');", reasoning: '마루의 번호 5와 허용된 상태 값 신청으로 고치면 FK와 CHECK를 모두 만족해요.', commonMistakes: ['status를 따옴표 없이 쓰는 것'] },
    conceptTags: ['DDL·제약조건'],
    successMessage: '제약조건에 맞게 INSERT를 고쳤어요.',
    config: {
      kind: 'sql-editor',
      starterSql: "INSERT INTO camp_signup(student_id, camp_name, status)\nVALUES (9, 'SQL캠프', '대기');",
      solutionSql: "INSERT INTO camp_signup(student_id, camp_name, status) VALUES (5, 'SQL캠프', '신청')",
      ordered: true,
      allow: ['insert'],
      stateCheckSql: 'SELECT student_id, camp_name, status FROM camp_signup ORDER BY student_id, camp_name',
      explore: [{ label: '표 정의 보기', sql: "SELECT sql FROM sqlite_schema WHERE name = 'camp_signup';" }],
    },
  }),
  defineActivity({
    id: 'U11-A04', unitId: 'U11', title: 'DDL·DML·TCL·DCL 분류',
    objective: 'SQL 명령을 종류별로 분류하고 DELETE/TRUNCATE/DROP 차이를 안다.',
    estimatedMinutes: 6,
    explanation: 'DDL은 구조(CREATE, ALTER, DROP, TRUNCATE), DML은 데이터(INSERT, UPDATE, DELETE, MERGE), TCL은 트랜잭션(COMMIT, ROLLBACK, SAVEPOINT), DCL은 권한(GRANT, REVOKE)을 다뤄요. DELETE는 행을 지우고 되돌릴 수 있지만, TRUNCATE는 모든 행을 빠르게 비우는 DDL이고 DROP은 표 자체를 없애요.',
    glossary: [
      { term: 'DCL', meaning: 'GRANT(권한 주기), REVOKE(권한 회수)처럼 권한을 다루는 명령' },
      { term: 'TRUNCATE', meaning: '표 구조는 남기고 모든 행을 비우는 DDL. 보통 ROLLBACK 불가(DBMS마다 다름)' },
    ],
    mode: 'simulation', datasetId: 'sandbox',
    prompt: '각 명령을 DDL, DML, TCL, DCL 중 하나로 분류하세요.',
    hints: [
      '표의 "모양"을 바꾸면 DDL, 표 "안의 행"을 바꾸면 DML이에요.',
      '확정·취소는 TCL, 권한은 DCL이에요.',
      'TRUNCATE는 행을 지우지만 DDL로 분류해요. MERGE는 DML이에요.',
    ],
    solution: { reasoning: 'CREATE/ALTER/DROP/TRUNCATE=DDL, INSERT/UPDATE/DELETE/MERGE=DML, COMMIT/ROLLBACK/SAVEPOINT=TCL, GRANT/REVOKE=DCL이에요.', commonMistakes: ['TRUNCATE를 DML로 고르는 것', 'GRANT를 DDL로 고르는 것'] },
    conceptTags: ['DCL', 'DELETE/TRUNCATE/DROP', 'TCL', 'DML', 'DDL'],
    dialectNotes: ['GRANT/REVOKE/TRUNCATE는 SQLite에 없어 실행하지 않는 개념 분류 활동이에요.'],
    successMessage: 'SQL 명령을 DDL·DML·TCL·DCL로 분류했어요.',
    config: {
      kind: 'classify', layout: 'bins',
      items: ['CREATE TABLE', 'ALTER TABLE', 'DROP TABLE', 'TRUNCATE TABLE', 'INSERT', 'UPDATE', 'DELETE', 'MERGE', 'COMMIT', 'ROLLBACK', 'SAVEPOINT', 'GRANT', 'REVOKE'].map((c) => ({ id: c.split(' ')[0].toLowerCase(), label: c })),
      options: [{ id: 'ddl', label: 'DDL' }, { id: 'dml', label: 'DML' }, { id: 'tcl', label: 'TCL' }, { id: 'dcl', label: 'DCL' }],
      answer: { source: 'static', map: { create: 'ddl', alter: 'ddl', drop: 'ddl', truncate: 'ddl', insert: 'dml', update: 'dml', delete: 'dml', merge: 'dml', commit: 'tcl', rollback: 'tcl', savepoint: 'tcl', grant: 'dcl', revoke: 'dcl' } },
    },
  }),
];
