import { defineCheckpointPair } from '../define';
import type { Question } from '../types';

const choice = (options: string[], correctIndex: number) => ({ type: 'choice' as const, options, correctIndex });
const num = (answer: number) => ({ type: 'number' as const, answer });
const sql = (solutionSql: string, ordered = false, starterSql = '', datasetId: 'school' | 'sandbox' | 'points' | 'clubs' = 'school') => ({ type: 'sql' as const, datasetId, solutionSql, ordered, starterSql });

/** 단원별 체크포인트 3문항 + 각 문항의 변형(재도전) 1문항 = 36 + 36 */
const pairs: [Question, Question][] = [
  /* ---------------- U01 ---------------- */
  defineCheckpointPair(
    { id: 'U01-Q01', unitId: 'U01', set: 'checkpoint', area: 'modeling', conceptTags: ['모델링', '추상화·단순화·명확화'],
      prompt: '모델링의 특징 중 "복잡한 현실에서 필요한 것만 남겨 쉽게 표현하는 것"은?',
      body: choice(['추상화', '단순화', '명확화', '정규화'], 1),
      explanation: '단순화는 복잡한 현실을 약속된 표기로 쉽게 표현하는 것이에요. 추상화는 공통 특징을 뽑아 일반화, 명확화는 애매함 없이 한 뜻으로 표현하는 것이에요.',
      review: '모델링의 세 특징: 추상화(공통 특징을 뽑아 일반화), 단순화(쉽게 표현), 명확화(한 가지 뜻으로 정확히). 각 단어의 뜻을 다시 떠올려 보세요.' },
    { prompt: '모델링의 특징 중 "누가 보아도 한 가지 뜻으로만 해석되도록 정확히 표현하는 것"은?',
      body: choice(['추상화', '단순화', '명확화', '반정규화'], 2),
      explanation: '명확화는 애매함을 없애 한 가지 의미로 해석되게 하는 것이에요.',
      review: '추상화·단순화·명확화 중 "애매함 없음"과 관련된 특징을 찾아보세요.' },
  ),
  defineCheckpointPair(
    { id: 'U01-Q02', unitId: 'U01', set: 'checkpoint', area: 'modeling', conceptTags: ['인스턴스', '엔터티'],
      prompt: "students 표에서 (3, '다온', 20, 2) 한 줄은 무엇에 해당할까요?",
      body: choice(['엔터티', '인스턴스', '속성', '도메인'], 1),
      explanation: '표의 한 행은 엔터티(학생)에 속한 하나의 대상, 즉 인스턴스예요.',
      review: '엔터티는 표 전체(대상의 묶음), 인스턴스는 그중 하나의 대상(행), 속성은 열이에요.' },
    { prompt: 'students 표의 grade(학년) 열은 무엇에 해당할까요?',
      body: choice(['엔터티', '인스턴스', '속성', '관계'], 2),
      explanation: '모든 학생이 공통으로 가진 특징인 학년은 속성(열)이에요.',
      review: '행은 하나의 대상, 열은 대상들의 공통 특징이에요.' },
  ),
  defineCheckpointPair(
    { id: 'U01-Q03', unitId: 'U01', set: 'checkpoint', area: 'modeling', conceptTags: ['개념/논리/물리 모델'],
      prompt: '데이터 타입(INTEGER, TEXT)과 인덱스를 정하는 일은 어느 모델링 단계일까요?',
      body: choice(['개념 모델', '논리 모델', '물리 모델'], 2),
      explanation: '특정 DBMS에 맞춰 타입·인덱스·테이블을 정하는 것은 물리 모델이에요.',
      review: '개념(큰 그림) → 논리(속성·식별자·정규화) → 물리(DBMS의 실제 구조) 순서로 구체화돼요.' },
    { prompt: '속성과 식별자를 정하고 정규화를 적용하는 일은 어느 모델링 단계일까요?',
      body: choice(['개념 모델', '논리 모델', '물리 모델'], 1),
      explanation: '속성·식별자·관계를 정확히 정하고 정규화하는 것은 논리 모델이에요.',
      review: '각 단계에서 하는 대표 작업을 다시 확인해 보세요.' },
  ),
  /* ---------------- U02 ---------------- */
  defineCheckpointPair(
    { id: 'U02-Q01', unitId: 'U02', set: 'checkpoint', area: 'modeling', conceptTags: ['함수종속', '1·2·3정규형'],
      prompt: '기본키가 (student_id, course_id)인 표에서 student_name이 student_id에만 종속돼 있어요. 이 부분 종속을 없애는 정규형은?',
      body: choice(['1정규형', '2정규형', '3정규형', 'BCNF'], 1),
      explanation: '복합키의 일부에만 종속된 부분 종속을 없애는 것이 2정규형이에요.',
      review: '1정규형: 한 칸에 값 하나 / 2정규형: 부분 종속 제거 / 3정규형: 이행 종속 제거.' },
    { prompt: 'student_id → dept_id → dept_name처럼 일반 열을 거쳐 종속된 이행 종속을 없애는 정규형은?',
      body: choice(['1정규형', '2정규형', '3정규형', '반정규화'], 2),
      explanation: '이행 종속을 없애는 것이 3정규형이에요.',
      review: '부분 종속과 이행 종속의 차이를 떠올려 보세요.' },
  ),
  defineCheckpointPair(
    { id: 'U02-Q02', unitId: 'U02', set: 'checkpoint', area: 'modeling', conceptTags: ['식별/비식별 관계', 'PK/FK'],
      prompt: 'enrollment.student_id는 외래키이면서 기본키 (student_id, course_id)의 일부예요. 학생-수강 관계는?',
      body: choice(['식별 관계', '비식별 관계', '관계 없음'], 0),
      explanation: '부모의 키가 자식의 기본키 일부가 되면 식별 관계예요.',
      review: '부모 키가 자식의 "기본키 안에" 들어가는지 확인해 보세요.' },
    { prompt: 'students.dept_id는 외래키지만 students의 기본키(student_id)에는 들어가지 않아요. 학과-학생 관계는?',
      body: choice(['식별 관계', '비식별 관계', '다대다 관계'], 1),
      explanation: '부모 키가 자식의 일반 속성(외래키)으로만 쓰이면 비식별 관계예요.',
      review: '외래키가 기본키에 포함되는지가 식별/비식별을 가르는 기준이에요.' },
  ),
  defineCheckpointPair(
    { id: 'U02-Q03', unitId: 'U02', set: 'checkpoint', area: 'modeling', conceptTags: ['본질/인조 식별자'],
      prompt: '업무에는 원래 없지만 시스템이 1, 2, 3…처럼 자동으로 붙인 신청번호는 어떤 식별자일까요?',
      body: choice(['본질 식별자', '인조 식별자', '보조 식별자', '외부 식별자'], 1),
      explanation: '업무에 원래 없던 값을 편의상 만들어 붙이면 인조 식별자예요.',
      review: '식별자가 업무에서 자연히 생기는지(본질), 인위적으로 만든 것인지(인조) 구별해 보세요.' },
    { prompt: '업무 규칙상 원래 존재하는 (학년, 반, 번호) 조합처럼 업무에서 자연스럽게 생긴 식별자는?',
      body: choice(['본질 식별자', '인조 식별자', '대체 식별자', '외래 식별자'], 0),
      explanation: '업무에 원래 존재하는 식별자는 본질 식별자예요.',
      review: '식별자가 어디에서 왔는지(업무 vs 시스템) 생각해 보세요.' },
  ),
  /* ---------------- U03 ---------------- */
  defineCheckpointPair(
    { id: 'U03-Q01', unitId: 'U03', set: 'checkpoint', area: 'basic', conceptTags: ['SELECT', 'FROM'],
      prompt: 'students에서 모든 학생의 학번(student_id)과 이름(student_name)을 조회하세요.',
      body: sql('SELECT student_id, student_name FROM students', false, 'SELECT '),
      explanation: 'SELECT student_id, student_name FROM students; — 열을 쉼표로 나열하고 FROM에 표를 써요.',
      review: 'SELECT 뒤에는 열 목록, FROM 뒤에는 표 이름을 써요. 열 순서도 문제와 같게 맞춰 보세요.' },
    { prompt: 'courses에서 모든 강좌의 강좌명(course_name)만 조회하세요.',
      body: sql('SELECT course_name FROM courses', false, 'SELECT '),
      explanation: 'SELECT course_name FROM courses;',
      review: '필요한 열 하나만 SELECT에 쓰면 돼요.' },
  ),
  defineCheckpointPair(
    { id: 'U03-Q02', unitId: 'U03', set: 'checkpoint', area: 'basic', conceptTags: ['DISTINCT'],
      prompt: '다음 SQL의 결과는 몇 행일까요?',
      code: 'SELECT DISTINCT grade FROM students;',
      body: num(3),
      verify: { datasetId: 'school', sql: 'SELECT COUNT(*) FROM (SELECT DISTINCT grade FROM students)' },
      explanation: '학년 값은 3, 3, 2, 3, 1, 2이고 서로 다른 값은 1, 2, 3 세 개예요.',
      review: 'DISTINCT는 서로 다른 값만 한 번씩 남겨요. students의 grade 값을 모두 적어 보세요.' },
    { prompt: '다음 SQL의 결과는 몇 행일까요?',
      code: 'SELECT DISTINCT course_id FROM enrollment;',
      body: num(2),
      verify: { datasetId: 'school', sql: 'SELECT COUNT(*) FROM (SELECT DISTINCT course_id FROM enrollment)' },
      explanation: '수강 행의 강좌 번호는 101과 102 두 가지예요.',
      review: 'enrollment의 course_id 값 중 서로 다른 값을 세어 보세요.' },
  ),
  defineCheckpointPair(
    { id: 'U03-Q03', unitId: 'U03', set: 'checkpoint', area: 'basic', conceptTags: ['논리적 처리 순서', '별칭'],
      prompt: 'SELECT 절에서 붙인 별칭을 사용할 수 있는 절은? (논리적 처리 순서 기준)',
      body: choice(['WHERE', 'GROUP BY', 'HAVING', 'ORDER BY'], 3),
      explanation: 'SELECT는 5번째로 처리되고 ORDER BY만 그 뒤에 처리돼서 별칭을 쓸 수 있어요.',
      review: 'FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY. 별칭이 만들어진 뒤에 처리되는 절은?' },
    { prompt: 'SELECT 문에서 논리적으로 가장 먼저 처리되는 절은?',
      body: choice(['SELECT', 'FROM', 'WHERE', 'ORDER BY'], 1),
      explanation: '어느 표인지 먼저 정해야 하므로 FROM이 가장 먼저예요.',
      review: '행을 거르려면 무엇이 먼저 정해져 있어야 할까요?' },
  ),
  /* ---------------- U04 ---------------- */
  defineCheckpointPair(
    { id: 'U04-Q01', unitId: 'U04', set: 'checkpoint', area: 'basic', conceptTags: ['IS NULL', 'NULL'],
      prompt: '점수(score)가 기록되지 않은(NULL) 수강 행의 student_id, course_id를 조회하세요.',
      body: sql('SELECT student_id, course_id FROM enrollment WHERE score IS NULL', false, 'SELECT student_id, course_id\nFROM enrollment\nWHERE '),
      explanation: 'NULL은 = 로 비교할 수 없어서 IS NULL을 써요.',
      review: '= NULL은 항상 UNKNOWN이라 행이 남지 않아요. NULL을 확인하는 전용 연산자를 떠올려 보세요.' },
    { prompt: '점수가 기록된(NULL이 아닌) 수강 행의 student_id와 score를 조회하세요.',
      body: sql('SELECT student_id, score FROM enrollment WHERE score IS NOT NULL', false, 'SELECT student_id, score\nFROM enrollment\nWHERE '),
      explanation: 'IS NOT NULL로 값이 있는 행만 남겨요.',
      review: 'NULL이 아닌 것을 확인하는 연산자는 IS NULL의 반대예요.' },
  ),
  defineCheckpointPair(
    { id: 'U04-Q02', unitId: 'U04', set: 'checkpoint', area: 'basic', conceptTags: ['3값 논리', 'NULL'],
      prompt: '다음 SQL의 결과 값은?',
      code: 'SELECT COUNT(*) FROM enrollment WHERE score = NULL;',
      body: num(0),
      verify: { datasetId: 'school', sql: 'SELECT COUNT(*) FROM enrollment WHERE score = NULL' },
      explanation: 'score = NULL은 모든 행에서 UNKNOWN이라 남는 행이 없어 0이에요.',
      review: 'NULL과의 비교 결과는 TRUE/FALSE가 아니라 UNKNOWN이에요. WHERE는 TRUE인 행만 남겨요.' },
    { prompt: '다음 SQL의 결과 값은? (점수: 90, 80, 90, NULL, 70, 80)',
      code: 'SELECT COUNT(*) FROM enrollment WHERE score <> 80;',
      body: num(3),
      verify: { datasetId: 'school', sql: 'SELECT COUNT(*) FROM enrollment WHERE score <> 80' },
      explanation: '90, 90, 70 세 행이 남아요. NULL <> 80은 UNKNOWN이라 빠져요.',
      review: 'NULL 행이 <> 비교에서 남는지 생각해 보세요.' },
  ),
  defineCheckpointPair(
    { id: 'U04-Q03', unitId: 'U04', set: 'checkpoint', area: 'basic', conceptTags: ['BETWEEN', 'IN'],
      prompt: 'score BETWEEN 80 AND 90 과 같은 뜻의 조건은?',
      body: choice(['score > 80 AND score < 90', 'score >= 80 AND score <= 90', 'score >= 80 OR score <= 90', 'score IN (80, 90)'], 1),
      explanation: 'BETWEEN a AND b는 양 끝 값을 포함해요.',
      review: 'BETWEEN이 양 끝(80, 90)을 포함하는지 생각해 보세요.' },
    { prompt: 'course_id IN (101, 102) 와 같은 뜻의 조건은?',
      body: choice(['course_id = 101 AND course_id = 102', 'course_id = 101 OR course_id = 102', 'course_id BETWEEN 101 AND 103', 'course_id <> 103'], 1),
      explanation: 'IN 목록은 각 값과의 = 비교를 OR로 이은 것과 같아요.',
      review: 'IN은 "목록 중 하나와 같다"는 뜻이에요.' },
  ),
  /* ---------------- U05 ---------------- */
  defineCheckpointPair(
    { id: 'U05-Q01', unitId: 'U05', set: 'checkpoint', area: 'basic', conceptTags: ['COALESCE'],
      prompt: "SELECT COALESCE(NULL, NULL, 'X', 'Y'); 의 결과는?",
      body: choice(['NULL', "'X'", "'Y'", "'XY'"], 1),
      verify: { datasetId: 'school', sql: "SELECT COALESCE(NULL, NULL, 'X', 'Y')" },
      explanation: 'COALESCE는 왼쪽부터 처음 NULL이 아닌 값인 X를 돌려줘요.',
      review: 'COALESCE는 인자들을 왼쪽부터 보며 처음으로 NULL이 아닌 값을 골라요.' },
    { prompt: 'SELECT NULLIF(5, 5); 의 결과는?',
      body: choice(['5', '0', 'NULL', '오류'], 2),
      explanation: 'NULLIF(a, b)는 a와 b가 같으면 NULL을 돌려줘요.',
      review: 'NULLIF는 두 값이 같을 때 무엇을 돌려주나요?' },
  ),
  defineCheckpointPair(
    { id: 'U05-Q02', unitId: 'U05', set: 'checkpoint', area: 'basic', conceptTags: ['문자열 함수'],
      prompt: '학생 이름(student_name)과 이름의 글자 수를 조회하세요.',
      body: sql('SELECT student_name, LENGTH(student_name) FROM students', false, 'SELECT student_name, \nFROM students;'),
      explanation: 'LENGTH(student_name)이 글자 수를 돌려줘요.',
      review: '글자 수를 세는 함수 이름을 떠올려 보세요(SQL Server는 LEN).' },
    { prompt: '학과명(dept_name)과 학과명의 앞 두 글자를 조회하세요.',
      body: sql('SELECT dept_name, SUBSTR(dept_name, 1, 2) FROM departments', false, 'SELECT dept_name, \nFROM departments;'),
      explanation: 'SUBSTR(dept_name, 1, 2)는 첫 글자부터 두 글자를 잘라요.',
      review: 'SUBSTR(문자, 시작 위치, 길이) — 시작 위치는 1부터 세요.' },
  ),
  defineCheckpointPair(
    { id: 'U05-Q03', unitId: 'U05', set: 'checkpoint', area: 'basic', conceptTags: ['Oracle/SQL Server 차이', 'COALESCE'],
      prompt: 'Oracle의 NVL(score, 0)과 같은 결과를 내는 표준 SQL 식은?',
      body: choice(['NULLIF(score, 0)', 'COALESCE(score, 0)', 'CAST(score AS INTEGER)', 'ROUND(score, 0)'], 1),
      explanation: 'NVL(a, b)와 COALESCE(a, b)는 a가 NULL이면 b를 돌려줘요. SQL Server는 ISNULL(a, b)예요.',
      review: 'NULL을 다른 값으로 바꾸는 표준 함수를 떠올려 보세요.' },
    { prompt: 'SQL Server에서 두 문자열을 이어 붙일 때 주로 쓰는 연산자는?',
      body: choice(['||', '+', '&', '.'], 1),
      explanation: 'SQL Server는 +, Oracle과 SQLite는 ||를 써요.',
      review: 'DBMS별 문자열 결합 연산자 차이를 다시 확인해 보세요.' },
  ),
  /* ---------------- U06 ---------------- */
  defineCheckpointPair(
    { id: 'U06-Q01', unitId: 'U06', set: 'checkpoint', area: 'aggregate-join', conceptTags: ['COUNT(*)와 COUNT(열)', 'NULL 집계'],
      prompt: '다음 SQL의 결과 값은?',
      code: 'SELECT COUNT(score) FROM enrollment WHERE course_id = 101;',
      body: num(2),
      verify: { datasetId: 'school', sql: 'SELECT COUNT(score) FROM enrollment WHERE course_id = 101' },
      explanation: 'SQL캠프 행은 3개지만 다온의 점수가 NULL이라 COUNT(score)는 2예요.',
      review: 'COUNT(열)은 NULL을 세지 않아요. SQL캠프 수강 행의 점수를 확인해 보세요.' },
    { prompt: '다음 SQL의 결과 값은?',
      code: 'SELECT COUNT(*) FROM enrollment WHERE course_id = 101;',
      body: num(3),
      verify: { datasetId: 'school', sql: 'SELECT COUNT(*) FROM enrollment WHERE course_id = 101' },
      explanation: 'COUNT(*)는 NULL과 관계없이 행을 세어 3이에요.',
      review: 'COUNT(*)와 COUNT(열)의 차이를 떠올려 보세요.' },
  ),
  defineCheckpointPair(
    { id: 'U06-Q02', unitId: 'U06', set: 'checkpoint', area: 'aggregate-join', conceptTags: ['GROUP BY'],
      prompt: '강좌(course_id)별 수강 행 수를 course_id와 함께 조회하세요.',
      body: sql('SELECT course_id, COUNT(*) FROM enrollment GROUP BY course_id', false, 'SELECT course_id, COUNT(*)\nFROM enrollment\n'),
      explanation: 'GROUP BY course_id로 묶고 COUNT(*)로 그룹별 행 수를 세요.',
      review: '그룹으로 묶을 열을 GROUP BY 뒤에 써요.' },
    { prompt: '학년(grade)별 학생 수를 grade와 함께 조회하세요.',
      body: sql('SELECT grade, COUNT(*) FROM students GROUP BY grade', false, 'SELECT grade, COUNT(*)\nFROM students\n'),
      explanation: 'GROUP BY grade로 묶어 학년별 학생 수를 세요.',
      review: '무엇별로 묶는지가 GROUP BY 열이에요.' },
  ),
  defineCheckpointPair(
    { id: 'U06-Q03', unitId: 'U06', set: 'checkpoint', area: 'aggregate-join', conceptTags: ['HAVING'],
      prompt: '수강 행이 3개 이상인 강좌의 course_id를 조회하세요.',
      body: sql('SELECT course_id FROM enrollment GROUP BY course_id HAVING COUNT(*) >= 3', false, 'SELECT course_id\nFROM enrollment\nGROUP BY course_id\n'),
      explanation: '그룹 조건 COUNT(*) >= 3은 HAVING에 써요.',
      review: '집계 결과로 그룹을 거를 때 쓰는 절은 WHERE가 아니에요.' },
    { prompt: '학생이 2명 이상인 학과의 dept_id를 조회하세요.',
      body: sql('SELECT dept_id FROM students GROUP BY dept_id HAVING COUNT(*) >= 2', false, 'SELECT dept_id\nFROM students\n'),
      explanation: 'GROUP BY dept_id HAVING COUNT(*) >= 2',
      review: '그룹을 만든 뒤 그룹의 개수 조건을 거는 절을 써 보세요.' },
  ),
  /* ---------------- U07 ---------------- */
  defineCheckpointPair(
    { id: 'U07-Q01', unitId: 'U07', set: 'checkpoint', area: 'aggregate-join', conceptTags: ['CROSS JOIN'],
      prompt: '다음 SQL의 결과 값은? (학생 6명, 강좌 3개)',
      code: 'SELECT COUNT(*) FROM students CROSS JOIN courses;',
      body: num(18),
      verify: { datasetId: 'school', sql: 'SELECT COUNT(*) FROM students CROSS JOIN courses' },
      explanation: 'CROSS JOIN은 모든 조합을 만들어 6 × 3 = 18행이에요.',
      review: 'CROSS JOIN은 조건 없이 두 표 행의 모든 조합을 만들어요.' },
    { prompt: '다음 SQL의 결과 값은? (학과 4개, 강좌 3개)',
      code: 'SELECT COUNT(*) FROM departments CROSS JOIN courses;',
      body: num(12),
      verify: { datasetId: 'school', sql: 'SELECT COUNT(*) FROM departments CROSS JOIN courses' },
      explanation: '4 × 3 = 12행이에요.',
      review: '두 표 행 수를 곱해 보세요.' },
  ),
  defineCheckpointPair(
    { id: 'U07-Q02', unitId: 'U07', set: 'checkpoint', area: 'aggregate-join', conceptTags: ['INNER JOIN', '다중 테이블'],
      prompt: '수강 기록마다 학생 이름(student_name)과 강좌 이름(course_name)을 조회하세요.',
      body: sql('SELECT s.student_name, c.course_name FROM enrollment e JOIN students s ON s.student_id = e.student_id JOIN courses c ON c.course_id = e.course_id', false, 'SELECT s.student_name, c.course_name\nFROM enrollment e\n'),
      explanation: 'enrollment를 가운데 두고 students, courses와 각각 키로 조인해요.',
      review: '중간 테이블 enrollment가 학생과 강좌를 이어 줘요. 조인 조건 두 개가 필요해요.' },
    { prompt: '모든 학생의 이름과 학과 이름(dept_name)을 조회하세요.',
      body: sql('SELECT s.student_name, d.dept_name FROM students s JOIN departments d ON d.dept_id = s.dept_id', false, 'SELECT s.student_name, d.dept_name\nFROM students s\n'),
      explanation: 'students와 departments를 dept_id로 조인해요.',
      review: '두 표에 공통으로 있는 키 열을 찾아 ON에 쓰세요.' },
  ),
  defineCheckpointPair(
    { id: 'U07-Q03', unitId: 'U07', set: 'checkpoint', area: 'aggregate-join', conceptTags: ['LEFT JOIN', '외부조인'],
      prompt: '학생이 한 명도 없는 학과의 dept_name을 조회하세요.',
      body: sql('SELECT d.dept_name FROM departments d LEFT JOIN students s ON s.dept_id = d.dept_id WHERE s.student_id IS NULL', false, 'SELECT d.dept_name\nFROM departments d\n'),
      explanation: '학과 기준 LEFT JOIN 후 학생 쪽이 NULL인 행이 짝 없는 학과예요(NOT EXISTS도 정답).',
      review: '짝이 없는 행을 남기는 조인과, 짝이 없음을 확인하는 조건을 함께 써 보세요.' },
    { prompt: '아무도 수강하지 않은 강좌의 course_name을 조회하세요.',
      body: sql('SELECT c.course_name FROM courses c LEFT JOIN enrollment e ON e.course_id = c.course_id WHERE e.course_id IS NULL', false, 'SELECT c.course_name\nFROM courses c\n'),
      explanation: '강좌 기준 LEFT JOIN 후 수강 쪽이 NULL인 강좌예요.',
      review: '기준이 되는 표(강좌)를 왼쪽에 두세요.' },
  ),
  /* ---------------- U08 ---------------- */
  defineCheckpointPair(
    { id: 'U08-Q01', unitId: 'U08', set: 'checkpoint', area: 'advanced', conceptTags: ['다중행 서브쿼리', 'IN'],
      prompt: 'IoT캠프(102)를 수강한 학생의 이름을 조회하세요. (서브쿼리 또는 조인)',
      body: sql('SELECT student_name FROM students WHERE student_id IN (SELECT student_id FROM enrollment WHERE course_id = 102)', false, 'SELECT student_name\nFROM students\nWHERE '),
      explanation: 'IN (SELECT student_id FROM enrollment WHERE course_id = 102)로 수강생 번호 목록과 비교해요.',
      review: '여러 행을 돌려주는 서브쿼리와 함께 쓰는 연산자를 떠올려 보세요.' },
    { prompt: 'SQL캠프(101)를 수강하지 않은 학생의 이름을 조회하세요.',
      body: sql('SELECT student_name FROM students s WHERE NOT EXISTS (SELECT 1 FROM enrollment e WHERE e.student_id = s.student_id AND e.course_id = 101)', false, 'SELECT student_name\nFROM students s\nWHERE '),
      explanation: 'NOT EXISTS 또는 NOT IN (서브쿼리에 NULL이 없을 때)으로 찾아요.',
      review: '"없는 것"을 찾는 서브쿼리 패턴을 떠올려 보세요.' },
  ),
  defineCheckpointPair(
    { id: 'U08-Q02', unitId: 'U08', set: 'checkpoint', area: 'advanced', conceptTags: ['UNION/UNION ALL'],
      prompt: '다음 SQL의 결과 값은? (수강 6행, 강좌 3행)',
      code: 'SELECT COUNT(*) FROM (\n  SELECT course_id FROM enrollment\n  UNION ALL\n  SELECT course_id FROM courses\n);',
      body: num(9),
      verify: { datasetId: 'school', sql: 'SELECT COUNT(*) FROM (SELECT course_id FROM enrollment UNION ALL SELECT course_id FROM courses)' },
      explanation: 'UNION ALL은 중복을 남겨 6 + 3 = 9행이에요.',
      review: 'UNION ALL과 UNION의 중복 처리 차이를 떠올려 보세요.' },
    { prompt: '다음 SQL의 결과 값은?',
      code: 'SELECT COUNT(*) FROM (\n  SELECT course_id FROM enrollment\n  UNION\n  SELECT course_id FROM courses\n);',
      body: num(3),
      verify: { datasetId: 'school', sql: 'SELECT COUNT(*) FROM (SELECT course_id FROM enrollment UNION SELECT course_id FROM courses)' },
      explanation: 'UNION은 중복을 없애 101, 102, 103 세 행이에요.',
      review: 'UNION 후 남는 서로 다른 course_id를 세어 보세요.' },
  ),
  defineCheckpointPair(
    { id: 'U08-Q03', unitId: 'U08', set: 'checkpoint', area: 'advanced', conceptTags: ['상관 서브쿼리', '스칼라·인라인뷰'],
      prompt: '바깥 쿼리의 각 행 값을 받아 행마다 다시 실행되는 서브쿼리는?',
      body: choice(['스칼라 서브쿼리', '인라인 뷰', '상관 서브쿼리', '단일행 서브쿼리'], 2),
      explanation: '바깥 행의 값(s.student_id 등)을 참조하는 서브쿼리가 상관 서브쿼리예요.',
      review: '서브쿼리가 바깥 표의 열을 참조하는지가 기준이에요.' },
    { prompt: 'FROM 절에 쓰여 임시 표처럼 사용되는 서브쿼리는?',
      body: choice(['스칼라 서브쿼리', '인라인 뷰', '상관 서브쿼리', '다중열 서브쿼리'], 1),
      explanation: 'FROM 절의 서브쿼리를 인라인 뷰라고 해요.',
      review: '서브쿼리가 쓰인 위치(SELECT, FROM, WHERE)에 따라 이름이 달라요.' },
  ),
  /* ---------------- U09 ---------------- */
  defineCheckpointPair(
    { id: 'U09-Q01', unitId: 'U09', set: 'checkpoint', area: 'advanced', conceptTags: ['RANK/DENSE_RANK/ROW_NUMBER'],
      prompt: '점수 100, 90, 90, 80에 DENSE_RANK(높은 순)를 매기면 80점의 순위는?',
      body: choice(['2', '3', '4', '5'], 1),
      explanation: 'DENSE_RANK는 1, 2, 2, 3으로 순위를 건너뛰지 않아요.',
      review: 'DENSE_RANK는 동점 뒤에 순위를 건너뛰지 않아요.' },
    { prompt: '점수 100, 90, 90, 80에 RANK(높은 순)를 매기면 80점의 순위는?',
      body: choice(['2', '3', '4', '5'], 2),
      explanation: 'RANK는 1, 2, 2, 4로 동점 수만큼 건너뛰어요.',
      review: 'RANK = 나보다 높은 행의 수 + 1' },
  ),
  defineCheckpointPair(
    { id: 'U09-Q02', unitId: 'U09', set: 'checkpoint', area: 'advanced', conceptTags: ['PARTITION BY', 'RANK/DENSE_RANK/ROW_NUMBER'],
      prompt: '점수가 있는 수강 행마다 같은 강좌 안에서 점수 높은 순 ROW_NUMBER(동점은 student_id 작은 순)를 붙여 student_id, course_id, 번호를 조회하세요.',
      body: sql('SELECT student_id, course_id, ROW_NUMBER() OVER (PARTITION BY course_id ORDER BY score DESC, student_id) FROM enrollment WHERE score IS NOT NULL', false, 'SELECT student_id, course_id,\n  ROW_NUMBER() OVER ( ) AS rn\nFROM enrollment\nWHERE score IS NOT NULL;'),
      explanation: 'PARTITION BY course_id로 강좌마다 번호를 1부터 다시 매기고, ORDER BY score DESC, student_id로 순서를 정해요.',
      review: '"같은 강좌 안에서"는 구역(PARTITION) 나누기, "높은 순"은 정렬(ORDER BY … DESC)이에요.' },
    { prompt: '학생마다 같은 학과 안에서 학년 높은 순 DENSE_RANK를 붙여 student_id, dept_id, 순위를 조회하세요.',
      body: sql('SELECT student_id, dept_id, DENSE_RANK() OVER (PARTITION BY dept_id ORDER BY grade DESC) FROM students', false, 'SELECT student_id, dept_id,\n  DENSE_RANK() OVER ( ) AS dr\nFROM students;'),
      explanation: 'DENSE_RANK() OVER (PARTITION BY dept_id ORDER BY grade DESC)',
      review: 'OVER 안에 구역과 정렬을 함께 써요.' },
  ),
  defineCheckpointPair(
    { id: 'U09-Q03', unitId: 'U09', set: 'checkpoint', area: 'advanced', conceptTags: ['LAG/LEAD'],
      prompt: 'LAG(points) OVER (PARTITION BY student_id ORDER BY event_id)에서 각 학생의 첫 행 값은?',
      body: choice(['0', '그 행의 points', 'NULL', '이전 학생의 마지막 points'], 2),
      explanation: '구역의 첫 행에는 이전 행이 없어서 NULL이에요(기본값을 주면 그 값).',
      review: 'LAG는 같은 구역 안의 이전 행을 봐요. 첫 행에는 이전 행이 있을까요?' },
    { prompt: 'LEAD(points) OVER (PARTITION BY student_id ORDER BY event_id)에서 각 학생의 마지막 행 값은?',
      body: choice(['0', 'NULL', '그 행의 points', '다음 학생의 첫 points'], 1),
      explanation: '구역의 마지막 행에는 다음 행이 없어 NULL이에요.',
      review: 'LEAD는 같은 구역의 다음 행을 봐요. 구역을 넘어가지 않아요.' },
  ),
  /* ---------------- U10 ---------------- */
  defineCheckpointPair(
    { id: 'U10-Q01', unitId: 'U10', set: 'checkpoint', area: 'advanced', conceptTags: ['ROLLUP/CUBE/GROUPING SETS/GROUPING'],
      prompt: 'GROUP BY ROLLUP(A, B)가 만드는 그룹 조합은?',
      body: choice(['(A, B)', '(A, B), (A), ()', '(A, B), (A), (B), ()', '(A), (B)'], 1),
      explanation: 'ROLLUP은 오른쪽 열부터 하나씩 빼며 (A,B) → (A) → () 조합을 만들어요.',
      review: 'ROLLUP과 CUBE의 차이는 "모든 조합"을 만드는지예요.' },
    { prompt: 'GROUP BY CUBE(A, B)가 만드는 그룹 조합은?',
      body: choice(['(A, B)', '(A, B), (A), ()', '(A, B), (A), (B), ()', '(A), (B), ()'], 2),
      explanation: 'CUBE는 가능한 모든 조합 (A,B), (A), (B), ()를 만들어요.',
      review: '열 2개로 만들 수 있는 모든 부분 조합을 적어 보세요.' },
  ),
  defineCheckpointPair(
    { id: 'U10-Q02', unitId: 'U10', set: 'checkpoint', area: 'advanced', conceptTags: ['계층형 질의·셀프조인'],
      prompt: 'Oracle 계층형 질의에서 트리를 시작할 루트 행을 지정하는 절은?',
      body: choice(['CONNECT BY', 'START WITH', 'ORDER SIBLINGS BY', 'PRIOR'], 1),
      explanation: 'START WITH가 시작(루트) 행을 정하고, CONNECT BY PRIOR가 부모-자식 연결 방향을 정해요.',
      review: '시작점을 정하는 절과 연결 방향을 정하는 절을 구분해 보세요.' },
    { prompt: 'Oracle 계층형 질의에서 부모-자식 연결 방향을 지정하는 절은?',
      body: choice(['START WITH', 'CONNECT BY PRIOR', 'LEVEL', 'WITH RECURSIVE'], 1),
      explanation: 'CONNECT BY PRIOR club_id = parent_id처럼 부모에서 자식 방향을 정해요.',
      review: 'PRIOR가 붙은 쪽이 이전(부모) 행의 값이에요.' },
  ),
  defineCheckpointPair(
    { id: 'U10-Q03', unitId: 'U10', set: 'checkpoint', area: 'advanced', conceptTags: ['정규표현식'],
      prompt: "패턴 '^[0-9]{3}-[0-9]{4}-[0-9]{4}$' 에 맞는 값은?",
      body: choice(['010-1234-5678', '02-1234-5678', '010-123-4567', '01012345678'], 0),
      explanation: '숫자 3개-4개-4개가 정확히 맞아야 해요.',
      review: '{n}은 앞의 문자가 정확히 n번, ^와 $는 시작과 끝이에요.' },
    { prompt: "패턴 '^SQL' 에 맞는 값은? (대소문자 구분)",
      body: choice(['SQL캠프', 'MySQL', 'nosql', 'S-Q-L'], 0),
      explanation: "^SQL은 'SQL'로 시작하는 값만 맞아요.",
      review: '^는 문자열의 시작 위치를 뜻해요.' },
  ),
  /* ---------------- U11 ---------------- */
  defineCheckpointPair(
    { id: 'U11-Q01', unitId: 'U11', set: 'checkpoint', area: 'management', conceptTags: ['DELETE/TRUNCATE/DROP'],
      prompt: '표 구조는 남기고 모든 행을 빠르게 지우며, 보통 ROLLBACK할 수 없는 DDL 명령은?',
      body: choice(['DELETE', 'TRUNCATE', 'DROP', 'ALTER'], 1),
      explanation: 'TRUNCATE는 구조를 남기고 데이터를 비우는 DDL이에요. DELETE는 DML이라 ROLLBACK할 수 있어요.',
      review: 'DELETE·TRUNCATE·DROP이 각각 무엇을 남기는지 비교해 보세요.' },
    { prompt: '표의 구조와 데이터를 모두 없애는 명령은?',
      body: choice(['DELETE', 'TRUNCATE', 'DROP', 'UPDATE'], 2),
      explanation: 'DROP TABLE은 표 자체를 삭제해요.',
      review: '구조까지 없어지는 명령은 무엇일까요?' },
  ),
  defineCheckpointPair(
    { id: 'U11-Q02', unitId: 'U11', set: 'checkpoint', area: 'management', conceptTags: ['INSERT/UPDATE/DELETE/MERGE'],
      prompt: "camp_signup에서 status가 '취소'인 행을 삭제하세요.",
      body: { ...sql("DELETE FROM camp_signup WHERE status = '취소'", true, 'DELETE FROM camp_signup\nWHERE ', 'sandbox'), allow: ['delete'], stateCheckSql: 'SELECT * FROM camp_signup ORDER BY signup_id' },
      explanation: "DELETE FROM camp_signup WHERE status = '취소';",
      review: 'DELETE FROM 표 WHERE 조건 — 조건을 빼면 모든 행이 지워져요.' },
    { prompt: "camp_signup에서 status가 '신청'인 행을 모두 '취소'로 바꾸세요.",
      body: { ...sql("UPDATE camp_signup SET status = '취소' WHERE status = '신청'", true, 'UPDATE camp_signup\nSET ', 'sandbox'), allow: ['update'], stateCheckSql: 'SELECT * FROM camp_signup ORDER BY signup_id' },
      explanation: "UPDATE camp_signup SET status = '취소' WHERE status = '신청';",
      review: 'UPDATE 표 SET 열 = 값 WHERE 조건 형식이에요.' },
  ),
  defineCheckpointPair(
    { id: 'U11-Q03', unitId: 'U11', set: 'checkpoint', area: 'management', conceptTags: ['ACID'],
      prompt: '트랜잭션의 ACID 중 "작업이 모두 반영되거나 하나도 반영되지 않는다"는 성질은?',
      body: choice(['원자성(Atomicity)', '일관성(Consistency)', '고립성(Isolation)', '지속성(Durability)'], 0),
      explanation: '원자성은 all-or-nothing을 뜻해요.',
      review: 'ACID: 원자성(전부 or 전무), 일관성(규칙 유지), 고립성(서로 간섭 없음), 지속성(확정 후 유지).' },
    { prompt: '트랜잭션의 ACID 중 "COMMIT된 결과는 장애가 나도 사라지지 않는다"는 성질은?',
      body: choice(['원자성(Atomicity)', '일관성(Consistency)', '고립성(Isolation)', '지속성(Durability)'], 3),
      explanation: '확정된 결과가 영구히 유지되는 것은 지속성이에요.',
      review: '네 성질의 뜻을 하나씩 떠올려 보세요.' },
  ),
  /* ---------------- U12 ---------------- */
  defineCheckpointPair(
    { id: 'U12-Q01', unitId: 'U12', set: 'checkpoint', area: 'aggregate-join', conceptTags: ['DISTINCT', '다중 테이블'],
      prompt: 'AI컴퓨터(10) 학과 학생들이 수강한 강좌명(course_name)을 중복 없이 조회하세요.',
      body: sql('SELECT DISTINCT c.course_name FROM students s JOIN enrollment e ON e.student_id = s.student_id JOIN courses c ON c.course_id = e.course_id WHERE s.dept_id = 10', false, 'SELECT \nFROM students s\n'),
      explanation: '학생-수강-강좌를 조인하고 학과 조건을 건 뒤 DISTINCT로 중복을 없애요.',
      review: '여러 학생이 같은 강좌를 들으면 강좌명이 반복돼요. 반복을 없애는 키워드를 쓰세요.' },
    { prompt: 'IoT캠프(102)를 수강한 학생들의 학과명(dept_name)을 중복 없이 조회하세요.',
      body: sql('SELECT DISTINCT d.dept_name FROM enrollment e JOIN students s ON s.student_id = e.student_id JOIN departments d ON d.dept_id = s.dept_id WHERE e.course_id = 102', false, 'SELECT \nFROM enrollment e\n'),
      explanation: '수강-학생-학과를 조인해 102 조건을 걸고 DISTINCT를 써요.',
      review: '필요한 표를 차례로 조인하고 중복을 없애 보세요.' },
  ),
  defineCheckpointPair(
    { id: 'U12-Q02', unitId: 'U12', set: 'checkpoint', area: 'aggregate-join', conceptTags: ['LEFT JOIN', 'NULL'],
      prompt: '다음 SQL의 결과 값은?',
      code: 'SELECT COUNT(*)\nFROM students s LEFT JOIN enrollment e ON e.student_id = s.student_id\nWHERE e.score IS NULL;',
      body: num(3),
      verify: { datasetId: 'school', sql: 'SELECT COUNT(*) FROM students s LEFT JOIN enrollment e ON e.student_id = s.student_id WHERE e.score IS NULL' },
      explanation: '수강 없는 라온·마루 2행 + 점수가 NULL인 다온의 SQL캠프 1행 = 3이에요.',
      review: 'LEFT JOIN으로 생긴 NULL과, 원래 데이터의 NULL을 모두 세어 보세요.' },
    { prompt: '다음 SQL의 결과 값은?',
      code: 'SELECT COUNT(*)\nFROM students s LEFT JOIN enrollment e ON e.student_id = s.student_id\nWHERE e.student_id IS NULL;',
      body: num(2),
      verify: { datasetId: 'school', sql: 'SELECT COUNT(*) FROM students s LEFT JOIN enrollment e ON e.student_id = s.student_id WHERE e.student_id IS NULL' },
      explanation: '짝이 없는 학생(라온, 마루) 2행만 e.student_id가 NULL이에요.',
      review: 'e.student_id는 원래 NOT NULL이라, NULL이면 짝이 없다는 뜻이에요.' },
  ),
  defineCheckpointPair(
    { id: 'U12-Q03', unitId: 'U12', set: 'checkpoint', area: 'aggregate-join', conceptTags: ['HAVING', 'GROUP BY'],
      prompt: '학과별 평균 점수가 80 이상인 학과만 남길 때, 그 조건을 쓰는 절은?',
      body: choice(['WHERE', 'HAVING', 'ORDER BY', 'ON'], 1),
      explanation: '그룹의 집계 결과로 거르는 조건은 HAVING에 써요.',
      review: '그룹을 만든 뒤 그룹을 거르는 절을 떠올려 보세요.' },
    { prompt: '행 수를 줄이지 않고 각 행 옆에 순위를 붙이는 방법은?',
      body: choice(['GROUP BY', 'HAVING', '윈도우 함수(RANK() OVER …)', 'DISTINCT'], 2),
      explanation: '윈도우 함수는 행을 묶지 않고 값을 붙여요.',
      review: 'GROUP BY는 행을 줄이고, 윈도우 함수는 행을 그대로 둬요.' },
  ),
];

export const CHECKPOINTS: Question[] = pairs.map((p) => p[0]);
export const VARIANTS: Question[] = pairs.map((p) => p[1]);
