import { defineQuestion } from '../define';
import type { Question } from '../types';

const choice = (options: string[], correctIndex: number) => ({ type: 'choice' as const, options, correctIndex });
const num = (answer: number) => ({ type: 'number' as const, answer });

/** 최초 진단 5문항: XP 없음, 단원 잠금에 쓰지 않음. 처음 배우는 학생은 건너뛰어도 된다. */
export const PRE_DIAGNOSTIC: Question[] = [
  defineQuestion({ id: 'P01', unitId: null, set: 'pre', area: 'modeling', conceptTags: ['인스턴스'],
    prompt: '학생 명단 표에서 가로 한 줄(행)은 보통 무엇을 뜻할까요?',
    body: choice(['학생 한 명의 정보', '모든 학생의 이름', '표의 제목', '잘 모르겠어요'], 0),
    explanation: '표의 한 행은 대상 하나(학생 한 명)의 정보예요. U01에서 배워요.', review: '' }),
  defineQuestion({ id: 'P02', unitId: null, set: 'pre', area: 'basic', conceptTags: ['SELECT'],
    prompt: 'SQL의 SELECT는 주로 어떤 일을 할까요?',
    body: choice(['데이터를 조회한다', '표를 삭제한다', '컴퓨터를 끈다', '잘 모르겠어요'], 0),
    explanation: 'SELECT는 표에서 원하는 데이터를 꺼내 보는 명령이에요. U03에서 배워요.', review: '' }),
  defineQuestion({ id: 'P03', unitId: null, set: 'pre', area: 'basic', conceptTags: ['WHERE'],
    prompt: '"3학년 학생만" 고르는 것처럼 조건에 맞는 행만 남기는 SQL 절은?',
    body: choice(['FROM', 'WHERE', 'ORDER BY', '잘 모르겠어요'], 1),
    explanation: 'WHERE가 조건에 맞는 행만 남겨요. U04에서 배워요.', review: '' }),
  defineQuestion({ id: 'P04', unitId: null, set: 'pre', area: 'aggregate-join', conceptTags: ['집계 함수'],
    prompt: '행의 개수를 세는 SQL 함수는?',
    body: choice(['SUM', 'COUNT', 'MAX', '잘 모르겠어요'], 1),
    explanation: 'COUNT가 개수를 세요. U06에서 배워요.', review: '' }),
  defineQuestion({ id: 'P05', unitId: null, set: 'pre', area: 'aggregate-join', conceptTags: ['JOIN'],
    prompt: '학생 표와 학과 표를 같은 학과 번호로 이어 붙이는 것을 무엇이라 할까요?',
    body: choice(['JOIN', 'DELETE', 'COMMIT', '잘 모르겠어요'], 0),
    explanation: '두 표를 키로 연결하는 것이 JOIN이에요. U07에서 배워요.', review: '' }),
];

/**
 * 최종 진단 12문항: 모델링 2, 기본 조회·함수 3, 집계·조인 3, 활용 3, 관리구문 1.
 * 자체 제작 문항이며 공식 모의고사가 아니다. 점수는 SQLD 합격 예측이 아니다.
 */
export const FINAL_DIAGNOSTIC: Question[] = [
  defineQuestion({ id: 'F01', unitId: null, set: 'final', area: 'modeling', conceptTags: ['1·2·3정규형', '이상현상'],
    prompt: '정규화를 하는 가장 중요한 목적은?',
    body: choice(['조회 속도를 항상 빠르게 하려고', '중복을 줄여 입력·수정·삭제 이상현상을 막으려고', '표의 개수를 줄이려고', 'NULL을 없애려고'], 1),
    explanation: '정규화는 중복으로 생기는 이상현상을 없애는 것이 목적이에요. 조인이 늘어 조회는 느려질 수도 있어요.',
    review: 'U02 정규화 활동을 복습해 보세요.' }),
  defineQuestion({ id: 'F02', unitId: null, set: 'final', area: 'modeling', conceptTags: ['관계', '다대다 중간 테이블'],
    prompt: '학생과 강좌처럼 다대다(M:N) 관계를 관계형 DB로 구현하는 일반적인 방법은?',
    body: choice(['학생 표에 강좌 번호 열을 여러 개 만든다', '두 키를 함께 가진 중간(교차) 엔터티를 만든다', '두 표를 하나로 합친다', '관계를 표현하지 않는다'], 1),
    explanation: '수강(enrollment)처럼 두 키를 가진 중간 엔터티로 1:N 두 개로 풀어요.',
    review: 'U02 ERD와 U07 다대다 조인을 복습해 보세요.' }),
  defineQuestion({ id: 'F03', unitId: null, set: 'final', area: 'basic', conceptTags: ['AND/OR/NOT'],
    prompt: '다음 SQL의 결과 값은?',
    code: 'SELECT COUNT(*) FROM students WHERE grade = 3 OR dept_id = 30;',
    body: num(4),
    verify: { datasetId: 'school', sql: 'SELECT COUNT(*) FROM students WHERE grade = 3 OR dept_id = 30' },
    explanation: '3학년(가온, 나래, 라온) 3명 + 30번 학과(마루) 1명 = 4명이에요.',
    review: 'OR는 둘 중 하나만 참이어도 남아요.' }),
  defineQuestion({ id: 'F04', unitId: null, set: 'final', area: 'basic', conceptTags: ['NULL', '3값 논리', 'CASE'],
    prompt: "SELECT CASE WHEN NULL = NULL THEN 'Y' ELSE 'N' END; 의 결과는?",
    body: choice(["'Y'", "'N'", 'NULL', '오류'], 1),
    verify: { datasetId: 'school', sql: "SELECT CASE WHEN NULL = NULL THEN 'Y' ELSE 'N' END" },
    explanation: 'NULL = NULL은 UNKNOWN이라 WHEN이 참이 아니고 ELSE로 가요.',
    review: 'U04 NULL과 3값 논리를 복습해 보세요.' }),
  defineQuestion({ id: 'F05', unitId: null, set: 'final', area: 'basic', conceptTags: ['문자열 함수'],
    prompt: "학생 이름(student_name)과 '학년: 3' 형식의 문자열(학년 값을 이어 붙임)을 조회하세요.",
    body: { type: 'sql', datasetId: 'school', solutionSql: "SELECT student_name, '학년: ' || grade FROM students", ordered: false, starterSql: 'SELECT student_name, \nFROM students;' },
    explanation: "'학년: ' || grade 로 문자열을 이어 붙여요(SQL Server는 +와 형변환).",
    review: 'U05 문자열 함수와 결합 연산자를 복습해 보세요.' }),
  defineQuestion({ id: 'F06', unitId: null, set: 'final', area: 'aggregate-join', conceptTags: ['LEFT JOIN'],
    prompt: '다음 SQL의 결과 값은?',
    code: 'SELECT COUNT(*)\nFROM departments d LEFT JOIN students s ON s.dept_id = d.dept_id;',
    body: num(7),
    verify: { datasetId: 'school', sql: 'SELECT COUNT(*) FROM departments d LEFT JOIN students s ON s.dept_id = d.dept_id' },
    explanation: '학생 6명과 짝지은 6행 + 학생 없는 전기에너지 1행 = 7행이에요.',
    review: 'U07 LEFT JOIN 결과 행 수 세는 법을 복습해 보세요.' }),
  defineQuestion({ id: 'F07', unitId: null, set: 'final', area: 'aggregate-join', conceptTags: ['LEFT JOIN', 'GROUP BY'],
    prompt: '모든 강좌(수강생 없는 강좌 포함)의 강좌명과 평균 점수를 조회하세요.',
    body: { type: 'sql', datasetId: 'school', solutionSql: 'SELECT c.course_name, AVG(e.score) FROM courses c LEFT JOIN enrollment e ON e.course_id = c.course_id GROUP BY c.course_id, c.course_name', ordered: false, starterSql: 'SELECT c.course_name, \nFROM courses c\n' },
    explanation: '강좌 기준 LEFT JOIN 후 GROUP BY로 평균을 구해요. 수강생 없는 강좌의 평균은 NULL이에요.',
    review: 'U06 GROUP BY와 U07 외부조인을 함께 복습해 보세요.' }),
  defineQuestion({ id: 'F08', unitId: null, set: 'final', area: 'aggregate-join', conceptTags: ['자연 조인', 'ON/USING'],
    prompt: 'students NATURAL JOIN departments는 어떤 기준으로 두 표를 연결할까요?',
    body: choice(['모든 행의 조합', '이름이 같은 열(dept_id)의 값이 같은 행', '기본키끼리', '행 번호가 같은 행'], 1),
    explanation: 'NATURAL JOIN은 두 표에서 이름이 같은 모든 열의 값이 같은 행을 연결해요.',
    review: 'U07의 USING/NATURAL JOIN 비교 SQL을 다시 실행해 보세요.' }),
  defineQuestion({ id: 'F09', unitId: null, set: 'final', area: 'advanced', conceptTags: ['INTERSECT'],
    prompt: '다음 SQL의 결과 값은?',
    code: 'SELECT COUNT(*) FROM (\n  SELECT student_id FROM enrollment\n  INTERSECT\n  SELECT student_id FROM students WHERE grade = 3\n);',
    body: num(2),
    verify: { datasetId: 'school', sql: 'SELECT COUNT(*) FROM (SELECT student_id FROM enrollment INTERSECT SELECT student_id FROM students WHERE grade = 3)' },
    explanation: '수강한 학생 {1,2,3,6}과 3학년 {1,2,4}의 공통은 {1,2}라 2예요.',
    review: 'U08 집합 연산자를 복습해 보세요.' }),
  defineQuestion({ id: 'F10', unitId: null, set: 'final', area: 'advanced', conceptTags: ['OVER', '누적 집계'],
    prompt: '다음 SQL의 각 행에 나오는 값은? (점수: 90, 80, 90, NULL, 70, 80)',
    code: 'SELECT SUM(score) OVER () FROM enrollment;',
    body: num(410),
    verify: { datasetId: 'school', sql: 'SELECT SUM(score) OVER () FROM enrollment LIMIT 1' },
    explanation: 'OVER ()는 전체를 한 구역으로 보고 모든 행에 전체 합계 410을 붙여요.',
    review: 'U09 윈도우 함수의 OVER 범위를 복습해 보세요.' }),
  defineQuestion({ id: 'F11', unitId: null, set: 'final', area: 'advanced', conceptTags: ['ROLLUP/CUBE/GROUPING SETS/GROUPING'],
    prompt: 'camp_monthly(학과 3개)에서 GROUP BY ROLLUP(dept_name)의 결과는 몇 행일까요?',
    body: num(4),
    verify: { datasetId: 'monthly', sql: 'SELECT COUNT(*) FROM (SELECT dept_name, SUM(participants) FROM camp_monthly GROUP BY dept_name UNION ALL SELECT NULL, SUM(participants) FROM camp_monthly)' },
    explanation: '학과별 3행 + 전체 총계 1행 = 4행이에요.',
    review: 'U10 소계 조합 토글을 다시 해 보세요.' }),
  defineQuestion({ id: 'F12', unitId: null, set: 'final', area: 'management', conceptTags: ['DCL'],
    prompt: 'GRANT SELECT ON students TO user1; 은 어떤 종류의 명령일까요?',
    body: choice(['DDL', 'DML', 'TCL', 'DCL'], 3),
    explanation: 'GRANT/REVOKE는 권한을 다루는 DCL이에요.',
    review: 'U11 명령 분류 활동을 복습해 보세요.' }),
];
